### ISSUE TITLE
The dialog windows and menu pop ups make the app lose focus to windows underneath

### ISSUE THREAD

**Issue by sunilvaltix** [sbmpost/AutoRaise#1]
I am seeing some annoying and weird behavior. Let's say an app opens a File Choose dialog. If this dialog overlaps another app, it raises the window underneath after the delay, lowering the window which popped the dialog. So, I lose the app I was working on.

Same thing with menu pop ups. If I am in Firefox, I go to the apple menu bar and select file and move the mouse to any of the menu items, it will raise the window underneath that menu to the front.

Why is it not able to distinguish between the app's menu/dialog window vs the main window of another app?

Also, the Autoraise.delay is looked up in current working directory. In some cases, I run it as service, I can't control the current working dir. Is it possible to move that to my home dir i.e. always pick the file from ~/ instead of the current working dir.

**Comment by sbmpost** [comment]
> Same thing with menu pop ups. If I am in Firefox, I go to the apple menu bar and select file and move the mouse to any of the menu items, it will raise the window underneath that menu to the front.

@sunilvaltix Can you try with this version (see link below)?
https://github.com/sbmpost/AutoRaise/blob/fix-issue-1/AutoRaise

> Let's say an app opens a File Choose dialog. If this dialog overlaps another app, it raises the window underneath after the delay, lowering the window which popped the dialog.
Not sure how this can happen. I will need more details on this one. Can you describe the steps more precisely?

> In some cases, I run it as service, I can't control the current working dir.
That should not be too difficult, I will add it later in this branch.

**Comment by sbmpost** [comment]
> That should not be too difficult, I will add it later in this branch.

This is also done now, can you check if it works for you?

**Comment by Dimentium** [comment]
> > That should not be too difficult, I will add it later in this branch.
> 
> This is also done now, can you check if it works for you?

Hi,

I also feel this issue and now it's seems ok - no annoying switching from menus.

Thanks!

**Comment by sunilvaltix** [comment]
Thanks for fixing these issues. I will test it out today and let you know

**Comment by sunilvaltix** [comment]
It  looks like the menu bug is fixed. It still did not pick up AutoRaise.delay from my home folder.

There is still a file chooser dialog issue, which is hard to describe, where I lose focus inside the file chooser dialog and have to click couple of times to make selection. See if you can have firefox or chrome open a file from desktop  for upload etc. May be I should make a video capture?

**Comment by sbmpost** [comment]
Yes, a video capture would definitely help 👍

**Comment by sbmpost** [comment]
By the way, I did some more fine-tuning to the timeouts / code. You may want to test with the latest version using the same link:
https://github.com/sbmpost/AutoRaise/blob/fix-issue-1/AutoRaise

**Comment by Dimentium** [comment]
> It still did not pick up AutoRaise.delay from my home folder.

same.

but i use this script for starting app with my custom delay:

```
File: .config/ToggleAutoRaise.sh
#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

pgrep autoraise > null
if [ ! $? -eq 0 ]
then
    /usr/local/bin/autoraise -delay 3 &
    disown
else
    pkill autoraise
    echo Stopped AutoRaise
fi
```

**Comment by Dimentium** [comment]
> By the way, I did some more fine-tuning to the timeouts and enabled the -O3 compiler flag. You may want to test with the latest version using the same link. I have good results with a delay setting of 2 (now the default). https://github.com/sbmpost/AutoRaise/blob/fix-issue-1/AutoRaise

Now it's nice and default 40ms also feels good for me.
Thank!

**Comment by Dimentium** [comment]
> By the way, I did some more fine-tuning to the timeouts and enabled the -O3 compiler flag. You may want to test with the latest version using the same link. I have good results with a delay setting of 2 (now the default). https://github.com/sbmpost/AutoRaise/blob/fix-issue-1/AutoRaise

And a small issue:
only first character from AutoDelay.delay has been read:

```
❯ echo 1 > AutoRaise.delay
❯ sh ~/.config/ToggleAutoRaise.sh
Started with 20 ms delay...

❯ echo 9 > AutoRaise.delay
❯ sh ~/.config/ToggleAutoRaise.sh
Started with 180 ms delay...

❯ echo 10 > AutoRaise.delay
❯ sh ~/.config/ToggleAutoRaise.sh
Started with 20 ms delay...

❯ echo 20 > AutoRaise.delay
❯ sh ~/.config/ToggleAutoRaise.sh
Started with 40 ms delay...
```

**Comment by sbmpost** [comment]
@Dimentium It now always reads 2 characters from the ~/AutoRaise.delay file. You said there are still cases where it doesn't pick up on this file? Can you tell me when exactly this happens?

**Comment by Dimentium** [comment]
> @Dimentium It now always reads 2 characters from the ~/AutoRaise.delay file. 

confirm that. thanks! )

> You said there are still cases where it doesn't pick up on this file? Can you tell me when exactly this happens?

Hmmmm. Maybe it was @sunilvaltix?

**Comment by sunilvaltix** [comment]
One issue remaining is that it doesn't autoraise the window if it belongs to the same application. For example, if I have two chrome windows open, I point my mouse from one to another, it does not raise. But if I moved the mouse to firefox or some other window of another app, it works.

**Comment by Dimentium** [comment]
> One issue remaining is that it doesn't autoraise the window if it belongs to the same application. For example, if I have two chrome windows open, I point my mouse from one to another, it does not raise. But if I moved the mouse to firefox or some other window of another app, it works.
> 
> Surprisingly, it does this only for some apps: chrome, microsoft visual code studio. It doesn't do this for iTerm or Firefox e.g. Have no idea what is specific for chrome and code.

It is strange, but it works for VS Code on my mac. 
I dont have Chrome so I can not check for it.

https://imgur.com/a/hQlDHPI

**Comment by sunilvaltix** [comment]
That's interesting...hmm. May be I should try rebuilding from master? I don't remember when I picked it up.
