### ISSUE TITLE
Add option to not AutoRaise when switching Spaces (Desktops)

### ISSUE THREAD

**Issue by chrisaj** [sbmpost/AutoRaise#105]
When switching spaces I don't want to AutoRaise straight away as I can't reliably predict what will be underneath the cursor!

Add a flag to control what happens on a space change.

**Comment by sbmpost** [comment]
@chrisaj 
Thanks for the commit :)
I will test with the new behavior coming week.

**Comment by chrisaj** [comment]
Contents of my .AutorRaise file:

```
#AutoRaise config file
delay=10
focusDelay=5
warpX=0.5
warpY=0.1
scale=2.5
altTaskSwitcher=false
mouseDelta=0.1
ignoreSpaceChange=true
```

**Comment by sbmpost** [comment]
@chrisaj 

I have tested with your changes. In addition to that another option was introduced for setting the mouse poll interval. Both of these changes are now in this branch: https://github.com/sbmpost/AutoRaise/tree/add-poll-millis-and-ignore-space-changed-options

Accompanying this branch, there will be the UI counterpart which is currently being updated. It might take a while to get all of this released but at least you know things are moving.

**Comment by sbmpost** [comment]
@chrisaj I am about to merge PR#106. It contains an updated UI with the ignoreSpaceChange setting you requested.

**Comment by cadeniyi** [comment]
Thanks! the 3.6.0 seems to be working fine for me.
