### ISSUE TITLE
Excluding apps using the compiled app and GUI versions

### ISSUE THREAD

**Issue by hasantahir** [sbmpost/AutoRaise#107]
Hi @sbmpost 

I am trying to exclude a couple of apps and I notice that I can only do so by starting the app through the command line. I compile the app using the command:

```
make clean && make CXXFLAGS="-DOLD_ACTIVATION_METHOD -DEXPERIMENTAL_FOCUS_FIRST -DALTERNATIVE_TASK_SWITCHER" && make install
```

I tried both the GUI and non-GUI versions of the compiled app and they don't exclude the apps provided in the config file which is made according to instructions in #55. Below are the contents of my config file:

```
#AutoRaise config file
delay=0
focusDelay=2
warpX=0.5
warpY=0.5
scale=3.5
ignoreApps="TickTick,Zotero"
mouseDelta=11
verbose=true 
```

However, Zotero and TickTick are not ignored. Same when using the GUI version:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/11236148/186420963-043b0257-af83-4cdd-b56f-cf0fccb13011.png">

Yet when I call autoraise through the command line through the local copy:

```
./AutoRaise -delay 0 -focusDelay 2 -warpX 0.5 -warpY 0.5 -scale 2.5  -ignoreApps "TickTick,Zotero" -mouseDelta 5 -verbose true
```

both Zotero and TickTick are excluded. Any suggestions on what could be happening? Thanks

**Comment by sbmpost** [comment]
@hasantahir 

The GUI version totally ignores what is in the configuration file I am afraid. The GUI version stores its settings in a different place under the Preferences folder.

It is strange however that when adding those apps in the GUI, it doesn’t work as expected. Have you tried “TickTick,Zotero" with quotes? Or you can also try with Zotero alone and see if that is being picked up correctly in the GUI. If so, you may have uncovered a bug when adding multiple apps.

**Comment by hasantahir** [comment]
Thanks for the feedback. So tried inspecting the GUI version and there have been a few more abnormal behaviours.

1. The ignored app list changes when I restart the GUI version
2. Zotero alone works fine in the GUI version
3. Zotero and TickTick don't work even with "Zotero,TickTick" or "TickTick,Zotero" options
4. The warp feature permanently increases the cursor size which has to be changed back to normal from the preferences. In the video below, the cursor size was increased in one of the previous runs.
5. TickTick alone behaves abnormally

Hope that the screencast below explains the above better:

https://user-images.githubusercontent.com/11236148/186479614-a3c1b72c-f484-4bd8-a1f8-7b27bb718c51.mp4

**Comment by hasantahir** [comment]
Through the command line, things work fine:

https://user-images.githubusercontent.com/11236148/186480650-2105d79f-362d-414a-94b4-bf609c5b5f61.mp4

**Comment by sbmpost** [comment]
@hasantahir 
Thanks for the detailed screen recordings. It would seem the GUI version needs some polishing. I will have a look as soon as possible.

**Comment by sbmpost** [comment]
@hasantahir 
I tested the ignoreApps field of the GUI with Notes and TextEdit. Both are correctly ignored.
Can you do the following:

1. Start the GUI version
2. Write Zotero,TickTick (without quotes)
3. Hit the enter/return key

I think you may have missed step 3 (which probably should be explained better)

**Comment by hasantahir** [comment]
Great. Yes, upon hitting Enter key both apps are now excluded. Thank you!
