### ISSUE TITLE
Feature Request: raise on click, then pass the click through

### ISSUE THREAD

**Issue by ttarchala** [sbmpost/AutoRaise#113]
Hello

I've been trying AutoRaise for a couple of weeks now. Nice job. My preferred way so far is to disable the raise, and use autofocus only, because my main annoyance in MacOS is that when the window is not in focus, the first click brings it to focus and then is "lost", even if I click precisely on the screen element I want on a window that is fully in view, just not in focus. As my brain does not always track which window is in focus, that means that sometimes I click once, sometimes twice.

However, autofocus alone is also annoying as it changes the focus just on any random mouse movement, sometimes invisibly, and sometimes even on the way from the window to the menu etc. So my brain still has to track which window I am in.

I was thinking – would it be possible to have another option in AutoRaise to passthrough/reclick the first click of a mouse in a non-focused window? So that this first click _both_ raises the window and is  then used on the element in the window in which I clicked.

Hope my explanation is clear, and thank you in advance for considering my request.

**Comment by sbmpost** [comment]
@ttarchala 

Hi there! I recall a similar request in the past. You can find it under the closed issue #9. The bottom line is that it is not so easy to implement. Someone mentioned reprogramming the mouse button so this might help you out.

> However, autofocus alone is also annoying as it changes the focus just on any random mouse movement, sometimes invisibly, and sometimes even on the way from the window to the menu etc. So my brain still has to track which window I am in.

Yes I see how this is annoying. I recall someone using a tool in combination with AutoRaise that would draw a thick border around the window in use. That at least would help to know which window is focused (as it can indeed be very hard to see sometimes)

**Comment by ttarchala** [comment]
Hi @sbmpost 

Thanks for taking the time to answer my request. The idea about the mouse button is interesting, and makes me think that maybe this is possible in software entirely, without having to buy a new mouse, by reprogramming the left mouse click to always send Cmd+click instead? Perhaps one could use something like Karabiner, or Hammerspoon, to do that.

**Comment by muhamedkarajic** [comment]
I dont understand why is this so hard to program, you already have all the logic, you need to make it so that when its changing focus while clicking that it also dose another click. 

Command + click is not changing the focus
