### ISSUE TITLE
Feature Request - Warp the cursor when a window is moved to a new screen

### ISSUE THREAD

**Issue by hasantahir** [sbmpost/AutoRaise#115]
Greetings,

I hope this is relevant to Autoraise. With the ability to move the windows across the screens through the keyboard, is it possible to warp the cursor along the window to the new screen/desktop?

Autoraise already does this when switching apps through `⌘ + ⇥`. It would be **great** if the cursor could be 'warped' (hoping this is the correct term) when a given window is moved across screens/desktops.

Thanks!

**Comment by sbmpost** [comment]
@hasantahir 
Hi there. Thanks for this suggestion. A similar request was made somewhere in the long conversation of issue #94. But better to have this feature request as a separate issue. Thanks for reporting :) Not sure if it is easy to implement btw as it requires AutoRaise to know when the currently focused window changes its position.

**Comment by sbmpost** [comment]
@hasantahir 

I finally found some time to research this. Unfortunately it seems impossible to get notified about windows moving, unless the application itself wants to know. AutoRaise however is monitoring things on a higher level and therefore can only be notified about applications launching or activating.

**Comment by hasantahir** [comment]
Thanks for getting back on this @sbmpost. Appreciate you investing your time.
