### ISSUE TITLE
Issues with focusing Blender 

### ISSUE THREAD

**Issue by Hammers69** [sbmpost/AutoRaise#116]
Hi Stefan!
Thanks for Autoraise! It's awesome!

I'm having some issues with Blender however (currently on v 3.3.1 on Mac studio Monterey 12.6.1).

Admittedly, Blender might be doing unconventional window things... but here's my scenario:

I like having two Blender windows, each open on it's own monitor (using WIndow>New Window). For ages otherwise I've just stretched the main window across 2 monitors because there are frustrations with activating the second window, not least of all because Blender relies (in it's traditional and best config) on RMB to select objects etc. So moving my mouse to a second window and then RMB clicking to select doesn't work until you first left-click somewhere. Autoraise to the rescue!

My issue is that about 50% of the time, even once the window is focused (with the menu bar active), mouse input seems wrong in the new window. I am unable to RMB select, or MMB orbit in the 3D view correctly. When I MMB in the 3D view it zooms the view instead of orbiting.

This was my clue, since to zoom like in the viewport you can use CTRL-MMB, so it was behaving as if the CTRL key was being pressed of its own accord in the newly activated window.

And so in fact when this issue pops up (like I say it only happens about half the time when switching from one Blender window to the other) if I hit the CTRL key, the window then becomes fully activated. 

I'd love Autoraise to be reliably useful for this, my main working software. Let me know if you'd like any more info and thanks again for all your work!

Best,

Stephen H.

By the way I'm using the Gui version. Not savvy enough to build myself I'm afraid. Here are my settings:

![Screen Shot 2022-11-15 at 8 46 40 pm](https://user-images.githubusercontent.com/38600234/201904588-e6d350a9-2b38-4a39-baad-c460287131f3.png)

**Comment by sbmpost** [comment]
@Hammers69 
Thanks for the detailed report :)

I will have a look at this for sure, but I can't say exactly when. This is because I very recently became a father so lots of stuff going on ;-)

**Comment by Hammers69** [comment]
Thanks for looking Stefan, and big congrats! Enjoy your daddy time :)

**Comment by sbmpost** [comment]
https://user-images.githubusercontent.com/10278551/203628013-bbba6d32-382d-4c72-9106-2c3184c1b94a.mov

@Hammers69 
Hi there!
So I downloaded blender and configured it to use right click to select objects and AutoRaise settings match the ones you shared above. I recorded a video (using Apple QuickTime Player) in which I am selecting objects with right click but for some reason I can't reproduce the behaviour you are describing.

**Comment by sbmpost** [comment]
@Hammers69 
Is this issue this relevant? See also my message above.

**Comment by sbmpost** [comment]
@Hammers69 
Can I safely close this issue? I haven't heard back from you for a while.

**Comment by Hammers69** [comment]
@sbmpost sorry I missed your previous comment. Mind if I have another look before you close it?

**Comment by sbmpost** [comment]
@Hammers69 
> Mind if I have another look before you close it?

👍

**Comment by Hammers69** [comment]
Hi @sbmpost , I just had another experiment, and for whatever reason I'm having very little issue now. Certainly RMB is working fine. Still I get occasional (maybe 1 in 10 or 15) instances where after switching to the second window, MMB will zoom instead of orbiting - behaving as if Ctrl were pressed I guess.

In any case this is so inconsistent I can't imagine tracking it down, and it may just be an OS/Blender thing. Let's call it closed and I'll give Autoraise another proper go for a while. Thanks and hope all is well! - Stephen.

**Comment by sbmpost** [comment]
@Hammers69 
Ok. If you learn more feel free to re-open
