### ISSUE TITLE
developer cannot be verified error message

### ISSUE THREAD

**Issue by AdriFern** [sbmpost/AutoRaise#117]
Downloading master and running command below gives error
```
unzip -d ~ ~/Downloads/AutoRaise-master.zip
cd ~/AutoRaise-master && make clean && make && make install
```

“create-app-bundle.sh” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

**Comment by sbmpost** [comment]
@AdriFern 
Probably because OSX added the quarantined flag to the shell script. Most likely the latest OSX version does this as this is the first time I hear about it. To remove the quarantined flag use:

    sudo xattr -d com.apple.quarantine ./create-app-bundle.sh

Then run the make command again
