### ISSUE TITLE
Source of AutoRaise.dmg

### ISSUE THREAD

**Issue by kohnish** [sbmpost/AutoRaise#120]
I see AutoRaise.dmg in master.  

Would it be possible to disclose the source for this?  
I want to apply my patch (just use command,ctrl and option to disable autoraise) but it's impossible to get the icon in the status bar.

**Comment by sbmpost** [comment]
The source of the Ui is already online under AutoRaise-UI. It is not fully up-to-date however. I will update it when time allows me.

**Comment by kohnish** [comment]
[Found it]( https://github.com/sbmpost/AutoRaise-UI)  
Thanks!
