### ISSUE TITLE
Spaces are removed from config file, affecting ignoreApps option

### ISSUE THREAD

**Issue by jimparis** [sbmpost/AutoRaise#121]
Spaces are intentionally removed from the configuration file:
https://github.com/sbmpost/AutoRaise/blob/45b0ce09ee010b6b0809298de741837a2f233baa/AutoRaise.mm#L720-L721
but this breaks specifying ignored apps with spaces in their names, e.g.:
```
ignoreApps=Android Studio,IntelliJ IDEA
```
For that use case, I have to resort to command-line arguments.

**Comment by sbmpost** [comment]
@jimparis 

This should have been fixed in branch: [fix-collected-issues](https://github.com/sbmpost/AutoRaise/tree/fix-collected-issues)

It might take some time before going to master but at least we have a fix ;-)
