### ISSUE TITLE
I cant turn off raise

### ISSUE THREAD

**Issue by consaltus** [sbmpost/AutoRaise#122]
Hello! First of all, thanks for this great soft!
I just migrated from WIN, and this is a very important soft for me.

So I try to disable the raise function. I need autofocus, but I don't need the raise.
Am I correct to understand that I must use `-delay 0`?
If yes this isn't working for me.
![CleanShot 2023-01-12 at 12 53 23](https://user-images.githubusercontent.com/30024675/212060069-77b8b1f7-9891-44c8-95b7-2785abdc7d2e.png)

**Comment by sbmpost** [comment]
@consaltus 
Try with -delay 0 -focusDelay 1

0 = disabled 
1 = no delay (as soon as possible)
>1 = delay

Sidenote: there is also a version with a GUI. You may want to check the first part of the readme for that version.

**Comment by consaltus** [comment]
I found! Thank you!!!
