### ISSUE TITLE
Does not work on Warp app

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#123]
1. Install Warp (https://www.warp.dev/)
2. Open Warp
3. Start AutoRaise 
4. Focus on a window that is now the Warp terminal window
5. Move your cursor over the Warp terminal window

Expected: Window is focused/auto-raised

Actual: Window is not focused/auto-raised

**Comment by sbmpost** [comment]
@samholmes ok interesting, never heard warp terminal before ;-)

Will have a look when I find the time (hopefully soon)

**Comment by sbmpost** [comment]
@samholmes 
So I tried to check warp out, but it requires me to create an account which I find odd for just trying out their software. Until this changes, I am unable to test I am afraid. The next best thing I can think of is that you try to run AutoRaise from the commandline with -verbose true as explained in the README. Perhaps this allows me to deduce from the logs why it is not raising/focusing.

**Comment by sbmpost** [comment]
@samholmes 
It would seem the warp guys made a fix. Can you confirm this?

**Comment by sbmpost** [comment]
@samholmes 
Ok, thanks!

Closing this issue then :-)
