### ISSUE TITLE
Please add a toggle for disabling temporarily by holding the control key

### ISSUE THREAD

**Issue by braincident** [sbmpost/AutoRaise#125]
Thanks for your very handy app. Everything works just fine for me except one thing.

I'm usually using ctrl+XX hotkeys for some shortcuts, but I found ctrl key delays or not reacts for 1 or 2 times as long as I turn on AutoRaise.

I was wondering if you can add a toggle for the temporarily disabling feature, or let user to set keys to disable.

**Comment by sbmpost** [comment]
@braincident 
Maybe a toggle to switch between the option or control key could work. I will add it to the list for the next release. That may take some time though. If you need something before that time, you may consider compiling AutoRaise yourself according to the instructions in the readme. If you want help with that let me know.

**Comment by dreeves** [comment]
I'm probably misunderstanding but when I hold down ctrl it does in fact seem to disable AutoRaise. Like I hold down ctrl and then move the mouse around and no focus-follows-mouse or autoraising happens.

I hadn't realized that before but it seems like that will be handy now that I know about it, for the rare occasions when AutoRaise is confusing some app with a popup window or something.

**Comment by sbmpost** [comment]
@braincident 
The toggle is now part of branch: [fix-collected-issues](https://github.com/sbmpost/AutoRaise/tree/fix-collected-issues)

It will be released in about one or two weeks from now. Until that time you may consider compiling manually. See the README for directions on how to do that.

**Comment by sbmpost** [comment]
@braincident 
Closing as the toggle has been added. The ui dmg image has also been updated
