### ISSUE TITLE
Feature Request - Warp on Window Cycle

### ISSUE THREAD

**Issue by NewEngine8** [sbmpost/AutoRaise#127]
It would be useful if the warp feature worked on ⌘ ` (cycle through windows of the active app) to move the cursor to the active window.

**Comment by sbmpost** [comment]
@NewEngine8 

This would indeed be quite nice! Not sure if it possible though. You see: AutoRaise can be notified by OSX about activated applications but probably not about individual windows. I haven't researched this however so I might be speaking too soon. Either way: Thanks for reporting :-)

**Comment by sbmpost** [comment]
@NewEngine8 

So I looked into this and it would seem that it is unfortunately not possible to get notified about events for individual windows.
