### ISSUE TITLE
Clarity on downloading/opening disk image

### ISSUE THREAD

**Issue by RowanG1** [sbmpost/AutoRaise#130]
I struggled for a long time to get the downloaded disk image to work.

This is what worked for me:
1) Download .dmg
2) Double click downloaded .dmg in Finder.
3) In finder, look for mounted disk image on side bar at left.
4) Drag the AutoRaise.app into the Applications folder.
5) Then open AutoRaise from Applications.
6) Give permissions to AutoRaise in System/Accessibility
7) Right click the menu bar balloon at top, then select preferences
6) What worked for me is to set mouse delta to 0.1, and to enable on launch.

I feel similar instructions could be included in the Readme.

**Comment by sbmpost** [comment]
@RowanG1 
Done, thanks for this feedback :-)
