### ISSUE TITLE
Calling plist_options in brew is deprecated; use service.require_root instead

### ISSUE THREAD

**Issue by PyGeek03** [sbmpost/AutoRaise#132]
in file/line dimentium/homebrew-autoraise/autoraise.rb:29, homebrew raises a warning on the deprecation of plist_options.

Exact Warning:
Warning: Calling plist_options is deprecated! Use service.require_root instead.

**Comment by sbmpost** [comment]
@PyGeek03 
There is already a PR for this here: https://github.com/Dimentium/homebrew-autoraise/pull/4

Maybe you can remind @Dimentium of it?

**Comment by fredngo** [comment]
The PR https://github.com/Dimentium/homebrew-autoraise/pull/4 has been merged. This issue can be closed.
