### ISSUE TITLE
Make mac desktop logo more prominent when enabled?

### ISSUE THREAD

**Issue by af4ro** [sbmpost/AutoRaise#134]
The contrast for the logo in the desktop topbar, when AutoRaise is enabled right now, is very low for light backgrounds with dark mode on. 
<img width="32" alt="Screenshot 2023-04-28 at 9 23 13 AM" src="https://user-images.githubusercontent.com/12554659/235201839-6a3bbef5-6a30-49f1-a928-9c7ac2a9712d.png">

Can we make this dark/black instead so it's easier to tell AutoRaise is on?

**Comment by sbmpost** [comment]
@af4ro 
Which version of AutoRaise are you using? Also in the image you posted, I see a pink color which is strange.
