### ISSUE TITLE
How to hide status bar icon?

### ISSUE THREAD

**Issue by wladislaw353** [sbmpost/AutoRaise#135]
<img width="136" alt="image" src="https://user-images.githubusercontent.com/32577796/235304697-e5eecfdd-44d3-4ed2-a9b4-b7352c0700f3.png">

**Comment by sbmpost** [comment]
@wladislaw353 
Currently this is not configurable although I can see why you would want it. Something for the next release I suppose. If the icon is really annoying you can consider using the non ui version instead. The README explains how to build/make AutoRaise which you can then configure using a hidden .AutoRaise file in your home folder.

**Comment by wladislaw353** [comment]
@sbmpost, іs this function implemented in the last update?

**Comment by sbmpost** [comment]
@wladislaw353 seems I was a bit over enthusiastic closing issues. I will re-open it. However I do have a question for you. If let's say the icon was disabled, how would one re-enable it? Wouldn't it be better to just build a non ui version instead?

**Comment by wladislaw353** [comment]
@sbmpost for example open a window by launching an application

**Comment by sbmpost** [comment]
@wladislaw353 

I have given it some serious thought how it could be implemented. I thought of a custom preferences pane in system preferences, or hiding the icon until restart. None of these solutions feels adequate or requires quite a bit of code for a relative small feature. So I looked on the Internet and found this free tool:

https://github.com/dwarvesf/hidden

This seems like a viable solution perhaps?

**Comment by sbmpost** [comment]
@wladislaw353 

So I actually found a way to include the hide icon functionality in AutoRaise. Simply download v4.0.3 (the latest binary in master). You will see an "hide icon" option. The icon will be hidden until you restart AutoRaise.

Thanks for challenging me on this one ;-)

**Comment by wladislaw353** [comment]
@sbmpost  Great!!
