### ISSUE TITLE
Easy step by step for someone with no computer skills

### ISSUE THREAD

**Issue by DatNgoNYC** [sbmpost/AutoRaise#136]
hi!

Love the software and what it can do but I'm not very tech savvy. I downloaded the app and it works but I can't understand the guide to enable to focus without raise feature. Is there a step by step guide for a non-tech savvy person. Please.

**Comment by sbmpost** [comment]
@DatNgoNYC 

Did you follow the first 7 steps from the README?

    Quick start

    1. Download the [disk image](https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg)
    2. Double click the downloaded .dmg in Finder.
    3. In finder, look for mounted disk image on side bar at left.
    4. Drag the AutoRaise.app into the Applications folder.
    5. Then open AutoRaise from Applications.
    6. Give permissions to AutoRaise in System/Accessibility
    7. Right click the menu bar balloon at top, then select preferences

For focus only, simply drag the raise delay slider completely to the left as in the following screenshot:
<img width="544" alt="Screenshot 2023-04-12 at 10 46 37" src="https://user-images.githubusercontent.com/10278551/236152722-971ba5dd-8fc3-4a66-9804-17beb8aee480.png">

**Comment by DatNgoNYC** [comment]
oh my goodness these are literally the same steps you have in the readme. I have no idea what I did before but it was wrong! Sorry for the bother but thank you Stefan for the help. So grateful you've made this software accessible to the computer-illeterate like myself. A thousand thanks

**Comment by sbmpost** [comment]
@DatNgoNYC 
Well what could have happened is that the readme inside the dmg image isn't up-to-date. I will fix this. Thanks for reporting!
