### ISSUE TITLE
Raise & focus not work with Desktop

### ISSUE THREAD

**Issue by pantone337cc** [sbmpost/AutoRaise#137]
I have one window open for example Notes. I managing files on desktop then I want continue typing in Notes, but Notes dont focus automatic. I need click on it.

App works only from window to window, but not from Desktop to window.

**Comment by sbmpost** [comment]
@pantone337cc 

You are absolutely right. It would seem this got introduced in v3.7 in an attempt to make password dialogs not lose their focus. A fix is underway...

**Comment by pantone337cc** [comment]
@sbmpost 
The app doesn't seem to work with the Calculator app either.
