### ISSUE TITLE
The ignore apps field will not ignore apps

### ISSUE THREAD

**Issue by saylroad** [sbmpost/AutoRaise#139]
What I am trying to achieve:
I would like to enable autoraise only on a couple of apps only.

If I insert the app name in the "ignore apps" field, nothing changes.
<img width="553" alt="Screenshot 2023-05-19 at 10 37 02 PM" src="https://github.com/sbmpost/AutoRaise/assets/134105922/5b262d75-22fc-465a-b76c-1fc2cabbd8c1">

**Comment by sbmpost** [comment]
@saylroad 

Can you try without .app?

**Comment by saylroad** [comment]
Thank you for your feedback. 

I got it working by removing .app and removing extra spaces or words. For example "Brave Browser" does not work, while "Brave" alone does.

As last, I also cannot get the keyboard shortcut to work. I am on Ventura. Do you know what could be the problem?

<img width="546" alt="Screenshot 2023-05-20 at 13 42 05" src="https://github.com/sbmpost/AutoRaise/assets/134105922/ba4ddb04-1092-432d-9656-3d3505db7610">

**Comment by sbmpost** [comment]
@saylroad 

> As last, I also cannot get the keyboard shortcut to work. I am on Ventura. Do you know what could be the problem?

Sometimes keyboard shortcuts you assign are already in use by the operating itself. I suggest you check existing shortcuts via keyboard settings in System Preferences. I am still on Monterey myself so I don't know if it could be ventura related. It might as the plugin I am using for the keyboard shortcut isn't exactly recent.

**Comment by sbmpost** [comment]
@saylroad 
Can you try with the latest dmg binary, v3.8.2? I changed some versioning settings which may affect the keyboard shortcut plugin. See the top of the README in master for the download link (dmg file)

**Comment by saylroad** [comment]
Hi, I have tried the latest version but unfortunately the shortcut still does not work.

**Comment by saylroad** [comment]
Also I cannot get the ignore app field to work with some apps. It is unclear how I should type in the app name. In general it seems to work with apps that have 1 word without spaces, such as "Safari".
So for example the full app name with spaces "Adobe Photoshop 2023" won't work, but it does work if you type "Photoshop", while some other apps such as "Little Snitch" won't work at all, even if I type either "Little" or "Snitch".
It would be great if there would be an include only field, as I would like to use AutoRaise only with Finder.

**Comment by sbmpost** [comment]
@saylroad 
> Hi, I have tried the latest version but unfortunately the shortcut still does not work.

I can't test the shortcut problem ATM as I am not on Ventura. This will have to wait until I have upgraded am afraid.

> It would be great if there would be an include only field, as I would like to use AutoRaise only with Finder.

One idea would be some kind of toggle to reverse the logic of the Ignore Apps field. This could be something for a future release. If in the meantime you want to experiment with this, you might consider building AutoRaise yourself as per the README instructions. Note however this won't give you the UI version with preferences and all so you will have to configure those using a configuration file. To reverse the Ignore Apps logic in the code yourself, simply remove the ! symbol in the AutoRaise.mm file on line 1012

https://github.com/sbmpost/AutoRaise/blob/39d854a46e2e5ab058dc16ac3bda28f400412613/AutoRaise.mm#L1012

**Comment by saylroad** [comment]
Thank you for all your help. I will give it a try.
Your app is amazing and I hope to see new features in the future.
