### ISSUE TITLE
Proposal: be robust to imprecise mousing

### ISSUE THREAD

**Issue by dreeves** [sbmpost/AutoRaise#14]
As discussed in #8, it's frustrating when AutoRaise accidentally happens due to imprecise mousing, like when you're trying to click something near the edge of the window and the mouse drifts slightly outside the window for too long.

(The ideal solution, what Linux window managers do, is instant focus-follows-mouse with like 500ms delayed autoraise. But Apple doesn't allow for that. There's no such thing as focus-follows-mouse without autoraise.)

One idea from @sbmpost was to add padding or an artificial border so that you have to go beyond that extra padding before AutoRaise considers the mouse to have left the current window.

But that's fraught. It can interact weirdly with the exception where a window doesn't get autoraised if it would fully obscure the current window. Also if a window is peeking out at the edge of the screen then it means that window can never be autoraised!

Proposal:

1. An artificial border / padding is used to prevent the current window from losing focus if the mouse is only barely outside it.

2. Exception: if the mouse is at the edge of the screen, that's intentional. Conceptually, having the mouse at the screen edge is like having it way past the screen edge. That's where I'm trying to go and am only stopped by the screen edge. It's not imprecise mousing.

3. The "fully contained" exception only applies if the current window is truly fully contained -- no artificial border. We want to keep a window from totally disappearing. If it's peeking out, it's not totally disappearing.

**Comment by sbmpost** [comment]
@dreeves 
With all the improvements of late, is this issue still relevant do you think? Note that I have released also a binary with UI recently, see: https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg

**Comment by sbmpost** [comment]
@dreeves 
oops, seems this conversation was locked, I unlocked it.

**Comment by dreeves** [comment]
Affirmative! I'm on the GUI version now and it's so brilliant!

**Comment by sbmpost** [comment]
@dreeves 
Your feedback always puts a smile on my face :-)
Thanks!
