### ISSUE TITLE
adding margin for over active mouse pointer

### ISSUE THREAD

**Issue by kujohn** [sbmpost/AutoRaise#149]
Would it be possible to add margins to windows to not activate raise/focus? The use cases are for corner window resizing, buttons near the corner + over active mouse (too much coffee).

**Comment by sbmpost** [comment]
@kujohn 

You probably want to experiment with the mouseDelta setting to adjust mouse sensitivity. For example, setting it to a value of 2, will require the mouse to move at least 2 pixels each time the mouse position is polled before a focus/raise is considered. Another setting of influence would be the (focus)delay. See the README for more information.

P.S. In the past, a window border had been considered but this led to inconsistent behavior.

**Comment by sbmpost** [comment]
@kujohn 

I am about to close this issue. If you have any further comments, let me know.
