### ISSUE TITLE
Zim - Desktop Wiki, flickering right-click menu on with delay=0 focusDelay=1

### ISSUE THREAD

**Issue by stuaxo** [sbmpost/AutoRaise#151]
In Zim[1], I'm trying the experimental focus-follows mouse no-raise behaviour:

`$./AutoRaise -delay 0 -focusDelay 1`

Once Zim is installed, run the AutoRaise, built with the experimental options from the README, and right click the HOME text in the Index.

As you scroll up and down the menu it flickers - (if you stop AutoRaise it doesn't).

The App is based on Gtk, it's possible it might be an issue in all Gtk apps with popup menus (it might be possible to verify this relatively straightforwardly).

[1]
https://zim-wiki.org/downloads.html

MacOS Build
https://gitlab.com/dehesselle/zim_macos/-/releases

**Comment by sbmpost** [comment]
@stuaxo 

Thanks for the detailed report. Will have a look as soon as time allows me to.

**Comment by sbmpost** [comment]
@stuaxo 

> The App is based on Gtk, it's possible it might be an issue in all Gtk apps with popup menus

This could very well be the case. In the meantime however I created a fix for Zim specifically. Note however this might not make it to master. Instead I think I should be introducing a "ignoreWindowTitles" option as this would also solve #143. I am not sure when I find the time to do this, so therefore the quick fix in [this branch](https://github.com/sbmpost/AutoRaise/tree/151-exclude-zim-window)

**Comment by stuaxo** [comment]
Nice, that seems to work pretty well.

**Comment by sbmpost** [comment]
@stuaxo 

Well AutoRaise finds the Zim window below the menu, tries to focus it, but for some reason never gets it. Then it tries again when moving the mouse, and so on...

**Comment by stuaxo** [comment]
I installed Xcode, there's some quartz tool I can install that might let me query this ?

I'm extremely rusty on native Mac development having last tried in 2008.

**Comment by sbmpost** [comment]
@stuaxo 

I always developed this tool trying to leave Xcode out of the equation ;-). Instead I am relying on commandline g++. AutoRaise has a verbose flag to help debugging (see the README). There is one helpful thing about Xcode though. It has a menu somewhere called "Developer Tools" and in it there is a tool that allows you to investigate the window hierarchy and attributes and so forth. I am sometimes using it to debug cases like these. Hope this helps :-)
