### ISSUE TITLE
Focus on mousedown instead of hover as a way to solve most app issues

### ISSUE THREAD

**Issue by Ekershir** [sbmpost/AutoRaise#152]
This app has been a sanity-saver for me transitioning to Mac OS from Linux and Windows. Thank you! 

However, there still are some issues, mainly stemming from the way Mac handles window management:

(1) App-sub-windows close when the app loses focus, like the "View Options" sub-window in Finder (screenshot attached). (2) Some apps, like JetBrains, raise windows on focus, leading to an inconsistent and frustrating user experience. (3) Chrome apps or empty title windows face focus/raising problems, along with other miscellaneous issues.

These aren't necessarily the app's "fault" but more related to MacOS's design, which doesn't handle these non-native behaviors well.

One solution I propose would potentially solve these issues without creating non-native Mac behavior. The root problem is having to click a window to make it "active" before interacting inside, leading to multiple unnecessary clicks that reduce productivity as they happen thousands of times a day. If focus didn't move into an app window on hover but was activated on "mousedown," users could click anywhere on any window just once. Mousedown would trigger activation, and a click would follow, both occurring in one user action, similar to web interaction.

The one potential drawback of this approach is that the mouse pointer won't change according to links and buttons hovered on non-focused apps. I think this is less of an issue, though. But maybe a hover/mousedown toggle will be best.

I hope this explanation clarifies my thoughts. If needed, I can explain further in a live demonstration.

Lastly, I assume that you're developing the app in your free time, which might be challenging. If funding is required for ongoing development, I'm happy to help fund this or other features, as this app has saved my MacOS experience.

![CleanShot 2023-08-14 at 23 28 30](https://github.com/sbmpost/AutoRaise/assets/130175095/cee58e42-2b6b-44b1-97d6-ebc211714b17)

**Comment by sbmpost** [comment]
@Ekershir 
That is a detailed story you wrote there :-). Such feedback is always appreciated.

> (1) App-sub-windows close when the app loses focus, like the "View Options" sub-window in Finder (screenshot attached).

In some cases this indeed happens. If however in the same Finder window you right click a file and select "get info" this doesn't occur. This would indicate there is something special going on with the "View Options" sub-window. I will have a quick look what it could be. Even so, you are right there will always be exceptions like this.

(2) Some apps, like JetBrains, raise windows on focus, leading to an inconsistent and frustrating user experience.

Yes, absolutely true. In fact there is already a partial workaround in AutoRaise for jetbrains apps for its subwindows. Let's hope one day they will fix the raising.

(3) Chrome apps or empty title windows face focus/raising problems, along with other miscellaneous issues.

I might find a solution for the Chrome Apps at some point, but currently it is a problem indeed.

> If focus didn't move into an app window on hover but was activated on "mousedown," users could click anywhere on any window just once. Mousedown would trigger activation, and a click would follow, both occurring in one user action, similar to web interaction.

I can see how this would prevent having to click twice in a window before interacting with it. Note however that if I disable AutoRaise and then move my mouse over to another window and click the mouse *without releasing* it, MacOS nevertheless already activates the window. So for MacOS the actual click already happened before AutoRaise would be able to intervene and initiate the focus of that window. However I must confess that I haven't actually tried to see if AutoRaise could be faster than MacOS so this is worth a small investigation.

> Lastly, I assume that you're developing the app in your free time, which might be challenging. If funding is required for ongoing development, I'm happy to help fund this or other features, as this app has saved my MacOS experience.

Time is indeed limited. Then again I am relying on AutoRaise myself as well everyday so improving it also improves my daily MacOS experience. I am happy to hear this is also an improvement for you :-)

**Comment by Ekershir** [comment]
Thanks for the quick response.

Regarding Mac OS being faster to focus the window - my understanding is that MacOS brings focus on click event. The "mousedown" event occurs before "click" (order is mousedown, click, mouseup) - so, in theory, interjecting on mouse down should happen before Mac OS can execute focus or any other behavior.

Regarding this and PWA apps, I'd love to help fund the development of these features if it will help speed it up (especially the PWA apps since I'm using them all the time making Autoraise not working for me at least 50% of the time).

Thank you.

**Comment by Ekershir** [comment]
Apologies for the bombardment. I just noticed that Autoraise doesn't work on Mac OS Sonoma (Currently in Beta, releasing probably next month). I did manage to get it to work once by disabling it and re-enabling but when I try now it doesn't work so I'm not sure what caused it to work once but it did for what its worth. I tried removing the app and installing again. It didn't help.

**Comment by sbmpost** [comment]
@Ekershir 

> The "mousedown" event occurs before "click" (order is mousedown, click, mouseup)

I don't believe there is a mousedown event in the way you describe it. When I push the mouse button, and the internal switch of the mouse makes a audible click, only then MacOS will produce a mousedown event (this is speculation). Then upon releasing the mouse button, you get a mouse up and click event the order of which is not always the same. At least this is what I remember from an investigation I did a long time ago. Things may have changed.

However assuming the above is true, you can see that MacOS already activates a window on mousedown. That is: the moment the audible click inside the mouse occurs. There are no events before that. So I think if AutoRaise were to respond on mousedown as well, it would become a race whoever comes first. Worth investigating ;-)

**Comment by mnwdeverest** [comment]
"Focus on mousedown instead of hover": I wish it was possible somehow.

**Comment by mnwdeverest** [comment]
"Focusing afterwards gets us nothing. In other words: the idea sounds nice, but it can't be done as far as I can see. "
I'm sad :-( Thank you for checking though!

**Comment by sbmpost** [comment]
@Ekershir 
> Focus/Raise of Chrome Apps doesn't work (there is already an issue for this, see #144)

Can you check with this latest binary?
https://github.com/sbmpost/AutoRaise/blob/151-exclude-zim-window/AutoRaise.dmg

**Comment by ShirEkerling** [comment]
Didn't get notified about your comment for some reason. This is awesome! It works perfectly with Chrome apps, thank you very much. Please let me know if you want to get some additional feedback on things I noticed since then. Still using it every day. Thanks again!

**Comment by ShirEkerling** [comment]
Hi, I wanted to bring to your attention that MacOS Sonoma was released yesterday and AutoRaise does not work with it. I tried to download a fresh installation as well as using the one you suggested with the Chrome Apps fix but both did not work

**Comment by sbmpost** [comment]
@ShirEkerling 

Can you try to recompile as outlined in #147?

**Comment by ShirEkerling** [comment]
Doesn't seem to make any difference on my end

**Comment by ShirEkerling** [comment]
I did just notice that when the app loads for the first time, focus WILL move into a window for the first window that is opened but it will not move to any other window after it did for the first time

**Comment by ShirEkerling** [comment]
I saw the new update and it seems to work perfectly again. Thank you for the quick solution. I appreciate it very much!
