### ISSUE TITLE
autocomplete text box focus issue on app store

### ISSUE THREAD

**Issue by lickmycrit** [sbmpost/AutoRaise#153]
my setting
<img width="482" alt="image" src="https://github.com/sbmpost/AutoRaise/assets/56221242/eab5268c-db76-4308-8c8d-b4342552835a">

app version
AutoRaise & Launcher
Version 3.9.0, 2023-06-01

this is my setup for autoraise, the issue i'm facing is when i tried to click on autocomplete or search result from text box in app store it registered as taking over the focus making me unable to click on the result.
steps to recreate issue

1. open mac app store
2. type any app you tried to search
3. move the mouse cursor to the autocomplete/search result

**Comment by sbmpost** [comment]
Thanks for this detailed report. I am working on a fix which I will push to a branch asap. For these kind of corner cases I am planning to introduce a setting called ignoreWindowTitles. Until this setting is there, the fix will be hardcoded string specifically for the App Store search window.

**Comment by sbmpost** [comment]
@lickmycrit 
Can you check with this latest binary?
https://github.com/sbmpost/AutoRaise/blob/151-exclude-zim-window/AutoRaise.dmg
