### ISSUE TITLE
Security Agent Window and Google Chrome password autofill

### ISSUE THREAD

**Issue by hasantahir** [sbmpost/AutoRaise#155]
With the recent update of Google Chrome (Version 116.0.5845.140 (Official Build) (arm64), MacOS 13.5.1) having enhanced security measures, I noticed Autoraise freezes the `com.apple.SecurityAgent` window ID where one has to enter the user password for Chrome to complete password autofill.

I have tried to record my screen, hoping the issue is noticeable. I am using the GUI version of Autoraise v3.9.0 with the following settings:

![image](https://github.com/sbmpost/AutoRaise/assets/11236148/6f28d697-d1a2-427c-9e34-1e3867fcf0e9)
 
Video Explanation:

With Autoraise enabled, the focus is stolen from the `com.apple.SecurityAgent` window to Google Chrome as seen in the Karabiner-EventViewer. When I disable Autoraise (by clicking the balloon), the issue of stealing the focus disappears.

https://github.com/sbmpost/AutoRaise/assets/11236148/a5d58d53-6b1e-4d93-8e68-fb8ef5763826

--
Your help will appreciated as always.

Thanks,
Hasan

**Comment by sbmpost** [comment]
@hasantahir 

I was just about to make another release when your bug report came in. Fortunately, I was able to quickly determine the cause of the problem thanks to your excellent bug report. Everything is in master now and the password dialog should stay properly focused now.

**Comment by hasantahir** [comment]
That's awesome. Thanks a lot @sbmpost for such a swift response. Enjoying v4.0.2 already.
