### ISSUE TITLE
Intelij Idea Window Keeps Raising Despite Disabled Setting

### ISSUE THREAD

**Issue by JonathanP-Git** [sbmpost/AutoRaise#156]
Hello,

I've been using AutoRaise and for some reason, even though I have disabled the window raising feature, the IntelliJ IDEA window continues to raise when I move my cursor over it.

Thank you for looking into this issue.

**Comment by sbmpost** [comment]
@JonathanP-Git 

This is a bug in IntellIJ (all JetBrains apps actually). See #131.

To mitigate the situation somewhat, you can consider adding "IntellIJ IDEA" to the ignoreApps list.
