### ISSUE TITLE
Not working on MacOS Sonoma

### ISSUE THREAD

**Issue by p-gurbani** [sbmpost/AutoRaise#158]
Since I have updated my Macbook Air M1 to Sonoma public beta. It has stopped working. 

### Here are my observations:
1. The app works only a single time.
2. When I activate it, and move my mouse cursor to another window, it focuses on that window.
3. But after that single focus, the app seems to disable itself, and now when I move my cursor around, nothing happens.
4. But again if I press the shortcut key or use the menu icon to activate the app, the focus starts working again (but again for just a single focus).

**Comment by sbmpost** [comment]
@p-gurbani 

Does recompiling help? See also #147. Sonoma is still in beta so unexpected behavior is possible.

**Comment by elaw-fastly** [comment]
I just upgraded to Sonoma and AutoRaise.app was no longer working.
Here is what I went thru to fix it.

I sync'd the latest source code, recompiled, and installed the AutoRaise.app (overwriting the old one).
I ran ./AutoRaise (with various args) from the command line and it worked.

I launched the app and it asked for ability to control via accessibility, but it was already there.
It took me a bit to realize the existing permissions were for the version I had overwritten.
I had to go into System Settings > Privacy & Security > Accessibility then remove AutoRaise.
I had to kill off the running AutoRaise.app and restart it to get a fresh request to add Accessibility control.
I enabled it and it starting working again.

**Comment by ericslaw** [comment]
I just upgraded to Sonoma and AutoRaise.app was no longer working.
Here is what I went thru to fix it.

I sync'd the latest source code, recompiled, and installed the AutoRaise.app (overwriting the old one).
I ran ./AutoRaise (with various args) from the command line and it worked.

I launched the app and it asked for ability to control via accessibility, but it was already there.
It took me a bit to realize the existing permissions were for the version I had overwritten.
I had to go into System Settings > Privacy & Security > Accessibility then remove AutoRaise.
I had to kill off the running AutoRaise.app and restart it to get a fresh request to add Accessibility control.
I enabled it and it starting working again.

**Comment by sbmpost** [comment]
@ericslaw 

Thanks for letting me know. In the Readme there is indeed a highlighted remark about this just below the quick start section. Changing/updating accessibility settings can be quite frustrating. Unfortunately AutoRaise can't manage these settings itself so it can't be automated.
