### ISSUE TITLE
Compilation broken when not using -DEXPERIMENTAL_FOCUS_FIRST

### ISSUE THREAD

**Issue by jmechnich** [sbmpost/AutoRaise#160]
Code does not compile after yesterday's merge of #159 if EXPERIMENTAL_FOCUS_FIRST (and therefore FOCUS_FIRST) is not defined (originally reported [here](https://github.com/Dimentium/homebrew-autoraise/issues/8) by @IAmVisco).

Unfortunately, it does not seem to be done by just moving a few `#ifdef` and `#endif` statements to the right place.

**Comment by sbmpost** [comment]
@jmechnich 
fixed, thanks for reporting :-)
