### ISSUE TITLE
safari and stickies pro not working

### ISSUE THREAD

**Issue by sohate** [sbmpost/AutoRaise#162]
Just updated to the new version from 4.0.3 and app doesn't work anymore. Ventura 13.6 MacBook Air M1. Installed previous version, works just fine (4.0.2).

**Comment by sbmpost** [comment]
@sohate when installing a new version, sometimes MacOS messes up accessibility rights. To rule out this possibility I suggest you go to accessibility settings and find the AutoRaise app in the list. Then while it is selected, click the minus to remove it from the list. Also stop previous AutoRaise instances using the "Activity Monitor" app. And then follow the quick start instructions from the README. Please let me know if this solves the issue. If not, then perhaps the command line version can give some insights as to what is happening. I suggest you start it with -verbose true and see if anything weird in the log pops up.

**Comment by sohate** [comment]
@sbmpost Ok, it's works now, thanks! But the app isn't focusing on Stickies Pro (sticky note on my desktop). Really strange.

**Comment by sbmpost** [comment]
@sohate was safari and stickies also not working in 4.2? Or did it break with the latest version? Also, what settings do you use? Is raise enabled or focus only?

**Comment by sohate** [comment]
@sbmpost 1. Sorry, idk what to do with AutoRaise.mm, I just downloaded AutoRaise.dmg from here https://github.com/sbmpost/AutoRaise/tree/162-stickies-pro and it still doesn't work with StickiesPro (version 4.0.2 works fine).

2. https://www.veed.io/view/478062df-8343-4a94-ba1a-94ca49989ad6 here's the video, and let me give you a description:

I have two displays (macbook and external). Open full screen video in Safari and drag full screen video on external display. And, as you may see on video, AutoRaise doesn't work with full screen video on external display, it just doesn't focus, I have to click.

**Comment by sbmpost** [comment]
@sohate 

Note that GitHub also allows you to drag video content in the conversation.

**Comment by sohate** [comment]
@sbmpost 

https://github.com/sbmpost/AutoRaise/assets/81889148/9796afd0-031f-4f71-8a95-c63e3a1ecf2a

**Comment by sbmpost** [comment]
@sohate can you also make a screenshot of the AutoRaise preferences screen so I know what settings you are using.

**Comment by sohate** [comment]
@sbmpost 
<img width="658" alt="Screenshot 2023-10-10 at 00 32 21" src="https://github.com/sbmpost/AutoRaise/assets/81889148/a90e60af-b147-4989-9a9b-bc80410d202b">
If I off "Delay window focus" it doesn't work with full screen safari video too.

**Comment by sbmpost** [comment]
@sohate thank you :-) I will have a look asap. Probably somewhere tomorrow

**Comment by sbmpost** [comment]
@sohate 
I have updated the dmg with fixes for Safari and Stickies pro. You can find it here:
https://github.com/sbmpost/AutoRaise/blob/162-stickies-pro/AutoRaise.dmg

If you can try it out for a couple of days, then we can merge this to master.

**Comment by matgianesini** [comment]
Hello! Not to make a new issue, I'd just like to ask about AutoRaise not working on chrome apps in the version currently installed by brew. I understand that is not on this repo and that version is not the most up to date, I just wanted to ask if that bug has already been fixed here in the upstream repo?

**Comment by sohate** [comment]
Found a bug: AutoRaise don't work with Apple Podcasts app.

**Comment by sbmpost** [comment]
@matgianesini 

Which brew version are you running? If v4.0 or higher, then chrome apps should work. The latest brew formula is at v4.3. Perhaps you simple need to update?

**Comment by sbmpost** [comment]
@sohate 
> AutoRaise doesn't work with Apple Podcasts app.

Will have a look asap

**Comment by sbmpost** [comment]
@sohate 

Podcasts app should focus/raise properly now, you can use the same link for the dmg:
https://github.com/sbmpost/AutoRaise/blob/162-stickies-pro/AutoRaise.dmg

P.S: I noted in the settings screen that you uploaded, that you have both raise and focus enabled. You might want to try out focus only (disable raise) after all the fixes that were made.

**Comment by sohate** [comment]
@sbmpost thanks, it works with podcasts now, thanks! I love raise options, don't wanna turn it off.

**Comment by sbmpost** [comment]
@sohate if you haven't found any further issues, I will be merging this probably in a few moments from now. Is everything still working as expected?

**Comment by sohate** [comment]
@sbmpost Yes, everything works fine.

**Comment by sbmpost** [comment]
@sohate merged ;-)
