### ISSUE TITLE
unable to enable on launch via preferences

### ISSUE THREAD

**Issue by bradyab** [sbmpost/AutoRaise#168]
macOS sonoma 14.1 (23B74)

you can still do this manually via system settings -> login items -> adding autoraise.app to the list of programs

**Comment by sbmpost** [comment]
@bradyab 

Right click opens preferences whereas left click starts/stops AutoRaise. On the first left click, MacOS should show a message asking for additional permissions for AutoRaise. Did this happen in your case? It could be that a previous AutoRaise permission was "in the way". In the README  below the quick start instructions, additional details are provided. All in all, setting MacOS permissions isn't always intuitive and sometimes unstable/broken even.
