### ISSUE TITLE
How can I run ./AutoRaise -delay 2 -warpX 0.5 -warpY 0.5 automatically?

### ISSUE THREAD

**Issue by samwzlim** [sbmpost/AutoRaise#17]
How can I program macOS to run the command `./AutoRaise -delay 2 -warpX 0.5 -warpY 0.5` automatically on startup? This command is executed by right clicking on the Applications folder, and selecting new terminal tab here. I can't find a way for macOS to auto do this by its own on startup, rather I have to manually do it everytime i start the machine up. Any help would be much appreciated.

**Comment by sbmpost** [comment]
1) echo 2 > ~/AutoRaise.delay
2) echo "0.5 0.5" > ~/AutoRaise.warp
3) Add AutoRaise to Update System Preferences | Users & Groups | Login items

<img width="474" alt="Screenshot 2021-01-06 at 10 46 49 AM" src="https://user-images.githubusercontent.com/10278551/103754411-9b48c800-500c-11eb-8400-8ec9bb6ed924.png">

**Comment by kristian-94** [comment]
@sbmpost  , do you know if I can turn off the delay? (I don't really see the point of it) Putting `-delay 0` doesn't seem to do it.

```
./AutoRaise -delay 0 -warpX 0.5 -warpY 0.5

By sbmpost(c) 2021, usage:
AutoRaise -delay <1=20ms> [-warpX <0.5> -warpY <0.5>]
Started with 40 ms delay, warpX: 0.5, warpY: 0.5
```

Btw, great tool, thanks very much for it!

**Comment by sbmpost** [comment]
@kristian-94 If you set -delay 1, you actually disable the delay. You see, the code applies this logic:

    delay = 0: no window raise is scheduled at all
    delay >=1: a window raise is scheduled, the moment it becomes 1, raise it.

But I can see how this is counterintuitive, so perhaps it would be better to hide this logic and treat delay = 0 in the code as delay = 1 if you see what I mean ;-)

**Comment by dreeves** [comment]
A convention I've seen in other Unix tools is to treat -1 as "infinity":
-1: don't raise at all
0: raise immediately
1: raise when the delay count is 1
etc

And if 0 is technically impossible, I think it should give an explicit error rather than just being functionally equivalent to delay 1. See https://blog.beeminder.com/postel

**Comment by sbmpost** [comment]
@dreeves 
>  I think it should give an explicit error rather than just being functionally equivalent to delay 1.

What I proposed was to increase the command line provided delay always by 1. Internally, in the code 1 actually means 0 (i.e: no delay). So hiding this weird detail by simply doing a +1 to whatever delay value is provided on the command line, is consistent.

**Comment by dreeves** [comment]
Sounds perfect; makes sense now.

And sounds like I misunderstood the part about zero-delay being impossible.

Also, on reflection, my idea for specifying infinite delay is silly. That's the same as not running autoraise at all! (Which also has me confused as to why internally there's such a thing as "no window raise is scheduled at all". But now I'm really out of my depth!)

PS: Could autoraise be more cpu-efficient if POLLING_MS wasn't hardcoded but depended on the delay setting? Like if you're opting for a longer delay then autoraise can get away with less frequent polling. I guess that's pretty fraught though, since you do want the amount of delay to be nice and consistent even when it's long.

**Comment by sbmpost** [comment]
> Sounds perfect; makes sense now.

Well almost perfect. You see, it seems this tool is getting more popular by the day and I don't want to break compatibility. So if people have an AutoRaise.delay file in their home folder with delay = 2, I don't want it to suddenly be treated as delay = 3. So I am thinking not to change it and point people to this discussion if they have questions about the delay ;-)

> Which also has me confused as to why internally there's such a thing as "no window raise is scheduled at all"

I can see your confusion. I mean: why would AutoRaise itself if it needs to run? The answer lies within these lines of the code:

    if (mouseMoved || delayTicks || raiseTimes) {
        // do lots of work to see if an actual raise is needed
    }

So if delayTicks >= 1, we *might* want to do a raise which is further investigated in the do "do lots of work" part. If however delayTicks equals 0, then at least this part of the condition can be ruled out as a reason to do further work. Now of course I also could have said something like this:

    if (mouseMoved || delayTicks != -1 || raiseTimes) {
        // do lots of work to see if an actual raise is needed
    }

And let delayTicks count down to 0. But I didn't like the -1 in there and decided to shift everything by one to make things easier to understand code-wise. But I forgot to shift things back for the command line and now it seems we are stuck with it ;-p

> Could autoraise be more cpu-efficient if POLLING_MS wasn't hardcoded but depended on the delay setting?

Interesting thought! I suppose it could. Let's say you wanted delay = 4, with POLLING_MS set to 20. That gives us 80ms which can also be obtained by having delay = 2 and POLLING_MS set to 40. There is one caveat with this though. I think you indicated it yourself already:

> I guess that's pretty fraught though, since you do want the amount of delay to be nice and consistent even when it's long.

So in the worst case, we just checked if a raise is needed and immediately after the mouse moves. In the case of POLLING_MS set to 40, we then have to wait another 40ms to see it. So in general a lower POLLING_MS value is desirable to increase consistency, with the downside of course that the CPU usage goes up. I actually have been tweaking and tweaking it for quite some time and found 20ms to be the best value. By the way: of course the whole implementation could also have been event based, but doing so would make AutoRaise quite a bit more complicated. So I chose the polling approach ;-)

**Comment by dreeves** [comment]
Idea for something akin to a legacy redirect:

Come up with a new term, maybe one that emphasizes that the delay is measured in ticks, not seconds or milliseconds, like `delayticks` and make that the new official setting that behaves intuitively. The old `delay` can either be supported as a special case for backward-compatibility or else give an explicit error that explains the new setting.

Alternatively, drop the confusing "ticks" concept and say that the delay is given in milliseconds and give an explicit error if it's not a multiple of 20 or whatever the tick duration is. I don't think that's any worse than having to give an error when someone tries to choose "1.5 ticks" or something as their delay. An explicit error takes away all the confusion and forces the user to learn what they need to learn when they need to learn it while letting the majority (like those who like the default delay fine) be blissful in their ignorance with no surprises or confusion for them.
