### ISSUE TITLE
Sonoma: Finder windows flickering

### ISSUE THREAD

**Issue by tkunze** [sbmpost/AutoRaise#170]
In Sonoma, when I move the mouse across the desktop, any Finder windows flicker like crazy. Any ideas what I can do to prevent this?

Config is:

```
delay=0
focusDelay=1
warpX=0.5
warpY=0.5
scale=1.0
mouseStop=true
```

Movie:

https://github.com/sbmpost/AutoRaise/assets/239703/29a6992c-81ba-49db-8b6c-e0288bca41fd

**Comment by sbmpost** [comment]
@tkunze 

@tkunze 

I can't reproduce the behavior you are seeing. Are you running the latest AutoRaise version? There have been some fixes for Sonoma and Finder in particular. There is also a GUI version (dmg) version which you may find useful for quickly adjusting settings.

**Comment by tkunze** [comment]
I was using the newest homebrew version, 4.6. ran another `brew upgrade autoraise` today, just to be sure.

When I run `/usr/local/bin/autoraise -delay 1 -focusDelay 1`, no flicker.
When I run `/usr/local/bin/autoraise -delay 0 -focusDelay 1`, flickering. (Setting focusDelay higher slows down the flickering.)

Same with the AutoRaise.app (4.6.0). As soon as I set the "Delay" slider to 0 (left-most setting), windows flicker.

**Comment by tkunze** [comment]
Update: created a new, vanilla user account and it works as advertised. Any idea what I could look for that's causing the flickering behavior in my user account?

**Comment by tkunze** [comment]
Update 2: If I _disable_ System Settings > Desktop & Dock > Show Items > On Desktop then there is no flickering. See screen below.

![Screenshot 2023-11-07 at 12 12 17](https://github.com/sbmpost/AutoRaise/assets/239703/ad0dc8fb-c3fe-4d2c-857d-1ce6c61343e1)

**Comment by tkunze** [comment]
Update 3: If I _click on the Desktop_ (triggers Expose in Sonoma now), then click again (to exit Expose), then there is _no flickering_. However, once I mouse over a couple of other application windows and back over the desktop, the flickering is back.

**Comment by tkunze** [comment]
Update 4: As with the option mentioned in [Update 2](https://github.com/sbmpost/AutoRaise/issues/170#issuecomment-1799910415), this issue also seems to be perfectly correlated to whether the menubar is set to hide or not, see screen below. If the menubar is set to hide "Always", finder windows flicker, if not, they don't flicker.

**Note**: Both, setting the menubar to never hide and setting [desktop items not to show](https://github.com/sbmpost/AutoRaise/issues/170#issuecomment-1799910415) *each* also fix #169.

**Comment by sbmpost** [comment]
@tkunze 
Lots of updates :-) 

Will have a look asap. I think with the detailed information you gave, I should be able to reproduce it. I will let you know.

**Comment by tkunze** [comment]
Unfortunately this is not quite conclusive yet. While turning these settings off fixes the flickering in _my_ account, turning them on in a vanilla account does not cause flickering…

I'll keep observing/diagnosing this on my end as well.

**Comment by sbmpost** [comment]
@tkunze 
I think in some cases, the desktop window (Finder) is seen as a main window. The circumstances under which this happens are still unclear to me. However I can prepare a debug version in which the desktop window is identified as such and never treated as a main window. On my machine I am indeed unable to reproduce what you are seeing. By the way, could it be that you are running additional tools to improve the MacOS GUI experience? It could be that these interact in unforeseen ways with AutoRaise under your account.

**Comment by tkunze** [comment]
Yes, looking at high-detail logs would be the next step. I already tried command line with `-verbose` but didn't see anything unusual.

I am not running any additional tools that mess with the window manager or the mouse operation. At least not to my knowledge. I suspect some setting in System Settings.app. I quit the obvious background daemons like Google drive, Dropbox, Keyboard Maestro, etc. before testing.

There is something in my desktop environment that messes things up, it seems.

**Comment by sbmpost** [comment]
@tkunze good news. I finally managed to reproduce. The conditions are:

- Use a single screen
- Menubar and Dock hidden

In this case the desktop window is seen as a full screen window which in turn means it is treated as a main window.
I have pushed the fix and merged with master. Thanks for the detailed reports. I think #169 should also be fixed now.

**Comment by tkunze** [comment]
Yay! That seems to fix it. Thank you!! 
AutoRaise is the best.
