### ISSUE TITLE
Not an Issue: Thanks for this tool

### ISSUE THREAD

**Issue by jyeung79** [sbmpost/AutoRaise#172]
Not an issue as the title suggested. Just want to shout out and thank y'all for this great tool. I miss auto focus since using Linux and this has been such a great replacement on MacOS. Makes using MacOS much more intuitive and productive.

Shout out to all the devs who worked on this 🙌 @Dimentium @sbmpost @fathah1

**Comment by stuaxo** [comment]
Also - thanks - one of the worst things in MacOS without Autoraise is the "bong" when you type into the wrong window and Autoraise fixes this.
