### ISSUE TITLE
After asking for accessibility permissions, wait until they are set and continue.

### ISSUE THREAD

**Issue by stuaxo** [sbmpost/AutoRaise#174]
When building and installing it can be a bit of a chore to kill the app and relaunch after the setting the permissions.

If AutoRaise doesn't have the accessibility permissions it needs, is there anyway it could wait until it does, and then continue (or restart) at that point?

**Comment by sbmpost** [comment]
@stuaxo

I tried in the past to detect this, but somehow it isn't reliable. Things may have changed though so perhaps this can be improved. It will require some research.

Thanks for reporting :-)
