### ISSUE TITLE
Invert the "Ignore Apps" list or create a "Only Apply to" list.

### ISSUE THREAD

**Issue by spookydracula** [sbmpost/AutoRaise#176]
A functionality to only use focus and raise on certain apps would be great, i use this when i have two fullscreen apps sharing a space and i want to use BetterTouchTool gestures between two apps and having focus in this situation is imperative.

Ignoring every single app on my system but say, 6 apps would be a chore.

Thank you!
spooky

**Comment by sbmpost** [comment]
@spookydracula 
Hi there! Yes inverting the app list is a good idea. Note it is very easy to temporarily adjust this in the code yourself. But having this as an option is obviously the way to go. Thanks for reporting!

**Comment by spookydracula** [comment]
Thank you for the quick response...another weird thing is that because so much of the icon is translucent, sometimes when you try to click it in Finder or Launchpad, you can’t select it...weird.

**Comment by sbmpost** [comment]
> sometimes when you try to click it in Finder or Launchpad, you can’t select it...weird.

Weird indeed. I usually use cmd-space to start AutoRaise so I never noticed. The transparency is for dark mode. Otherwise the icon won't be visible.

**Comment by fullstackneo** [comment]
+1

**Comment by spookydracula** [comment]
awesome. thank you!

**Comment by fullstackneo** [comment]
I just tested the new 'invert', looks like it will actually exclude all apps including the ignore apps.

https://github.com/sbmpost/AutoRaise/assets/97574983/02cea394-ece0-4da1-957b-569eb65e8fe6

**Comment by sbmpost** [comment]
@fullstackneo 

The applications in that list are not bundle identifiers. Try with "Chrome" only

**Comment by fullstackneo** [comment]
Yes, that works like a charm! @sbmpost

**Comment by sbmpost** [comment]
This will be merged with master in one week or so. I am closing the issue.
