### ISSUE TITLE
Option to keep delay ms whatever we want in app version

### ISSUE THREAD

**Issue by ishaanrathodd** [sbmpost/AutoRaise#178]
Would love to have an option to change the delay ms whatever we want between 0 and 500ms and not just 50,100,150ms,etc in the GUI app version, don't wanna go through the command line interface, the options are beyond my understanding🥲

**Comment by sbmpost** [comment]
@ishaanrathodd 

The delay steps depend on the mouse polling interval which can be changed in the bottom section of the UI. If for example you want 30, 60, 90, then simply change the polling interval to 30. Note that lowering the poll interval increases cpu usage. It is for this reason that the minimum is 20 to prevent your cpu going to 100%.

**Comment by darthkali** [comment]
I also looked for this option. Would be good to have a hint for this in the UI.
