### ISSUE TITLE
Doesn't seem to work on Silicon M1 Macs ?

### ISSUE THREAD

**Issue by cestbibi** [sbmpost/AutoRaise#18]
I can see the process is launched ok  in Activity Monitor but no autoraise nor warp seem to be working for me..

**Comment by sbmpost** [comment]
It should have asked for Accessibility permissions, which can be set in System Preferences.

<img width="666" alt="Screenshot 2021-01-06 at 10 42 07 AM" src="https://user-images.githubusercontent.com/10278551/103753933-f332ff00-500b-11eb-80cc-fd32b8f8f4f0.png">

**Comment by cestbibi** [comment]
My bad ! I missed this part. Thank you very much, works perfect now.  Happy new year and thank you for this, I missed this very useful feature ever since I saw it working in Linux a long time ago.

**Comment by sbmpost** [comment]
:-) nice to hear it works for you. closing this issue and happy new year to you too!
