### ISSUE TITLE
Enable autorise only when an external monitor is detected

### ISSUE THREAD

**Issue by hexclann** [sbmpost/AutoRaise#180]
Thanks for this amazing tool. When using an external monitor, you have to click to activate and then you can use the windows, is it possible to automatically enable autorise when using external monitor and disable when there is no external display connected?

**Comment by sbmpost** [comment]
@hexclann 

It would seem like this is more or less what is requested in issue #11. Would you agree? Issue #11 is on my radar but I can't give a time line as I am very busy atm.

**Comment by hexclann** [comment]
@sbmpost yes this is what I was looking for, sorry I didn't check previous issues. I'll close this subscribe to the already existing issue
