### ISSUE TITLE
Autoraises after mouse movement within window, not on initial entry

### ISSUE THREAD

**Issue by web3d0** [sbmpost/AutoRaise#181]
When flicking the mouse rapidly to a corner, the window doesn't auto-raise. Moving the mouse by one pixel subsequently raises (or focuses) the window.

This appears to be because AutoRaise is sampling the last mouse position, rather than the current mouse position. Eg, it is something like "if (movement) raise(last_position)", rather than "if (movement) raise(current_position)".

This problem can be replicated by flicking a finger across the mouse pad into another window, and seeing it doesn't activate.

**Comment by sbmpost** [comment]
@web3d0

Thinking a bit more about your description, perhaps the problem can be reduced by lowering the mouse polling interval (at the cost of higher cpu usage). You can use the bottom section in the UI for this, or if you are using the command line version, you can specify -pollMillis 20

**Comment by web3d0** [comment]
I'm a bit stuck on how to screen record the mouse movements, but will poke into it a bit more. I am flicking to the sides and bottoms of the screen with 50ms delay so I can get to the menu bar without changing apps along the way.

Some background information is that I use "Rectangle" to lay out my windows, so hot corners are turned off and I can flick to change windows. If I flick then move by one pixel, it works fine. If I flick, then sometimes it doesn't work.

I have tested flicking to the middle of a window, to the bottom or left/right edges, or to the corner, and it's the same problem where it needs at least one pixel of movement after rapidly moving between windows.

I think it is possibly the same issue as if you close a window, the the one underneath isn't AutoRaised unless you move a pixel.

I don't think it's a polling issue,  even though that would minimise the number of times the problem happens. It really does seem to be a "the last mouse position" rather than "current mouse position".

**Comment by sbmpost** [comment]
> I think it is possibly the same issue as if you close a window, the one underneath isn't AutoRaised unless you move a pixel.

It might indeed be the case. If this is true, there is not much that can be done about it I am afraid. AutoRaise relies on mouse polling to detect mouse movement and the mouse needs to move at least one pixel. For curiosity I checked what happens if I let AutoRaise believe the mouse moved even when it is not. As expected, CPU usage increases considerably. Theoretically it would solve your problem, but it introduces other unwanted side effects as well.

**Comment by web3d0** [comment]
Issue has been answered, no fix within scope of how this works.

**Comment by sbmpost** [comment]
@web3d0 

Thanks for the detailed write up. What AutoRaise does is a small variant of your code. What it does is:

   loop every 50 milliseconds:
       update_coord(current);
       activate_by_stored_coord();

The loop is unavoidable because an event based approach only works if you have direct access to the application itself. AutoRaise sits "above" multiple applications and therefore can only poll regularly (the loop) to obtain the global mouse position. That being said it still seems a bit strange it wouldn't detect the mouse movement. I will test this on my machine. I am not sure if I am able to "flick" the mouse. I think what you mean by that is very fast movement. I will give it a shot however.

**Comment by web3d0** [comment]
https://github.com/sbmpost/AutoRaise/assets/140585/fc522e7a-4180-415b-98e2-dfedd2ac9ecf

This shows normal window switching, then two failed attempts to move to the bottom right window, then one successful attempt as it sometimes works.

My thought is perhaps in your 50ms loop, there might sometimes be more than one event so you're processing the ones in a queue. The fix would be to check if there are more events?

**Comment by sbmpost** [comment]
@web3d0 

Video helps a lot :-) 
I will have a look when I find the time. Hopefully somewhere this week.

**Comment by web3d0** [comment]
It might not be the flick. I can replicate the problem by moving the mouse very slowly so it doesn't autoraise, and into the corner and it doesn't autoraise.

No matter how quickly I flick, if the mouse isn't at the edge of the screen or in the corner, it will always autoraise. So it's literally a corner case!

It's not related to the corner of the window, it's specifically related to edge or corner of screen.

**Comment by web3d0** [comment]
https://github.com/sbmpost/AutoRaise/assets/140585/279d9e32-adc4-4bb8-9dc5-4e5871eee205

Fast or slow doesn't matter. Dragging to an edge instead of the corner also has the bug, but half as much.

**Comment by sbmpost** [comment]
@web3d0 

Thanks again for diving deep into this. It helps me to understand what is going on. I think it has to do with the virtual border of a window that was added in monterey (a few mac os versions ago). I wrote a comment about it in the top section of the AutoRaise.mm file. I haven't actually tested this yet however.

**Comment by sbmpost** [comment]
@web3d0 
The problem should be reduced (mitigated) in branch AutoRaise-4.8. Especially if you lower the polling interval from 50ms to 20ms. If you can let me know if this is indeed an improvement, that would be great.

**Comment by web3d0** [comment]
Just seems a bit faster but hasn't really changed anything. Repeating the mouse movement results in the same percentage of failures as having it at 20ms in version 4.7.

I did notice another bug, but not sure whether it is related. If there is a one pixel gap, it won't raise the window underneath, even though it will if you click on it.

Want a video for that?

**Comment by web3d0** [comment]
![Screen Shot 2024-03-14 at 4 48 31 pm](https://github.com/sbmpost/AutoRaise/assets/140585/fe537af2-38c0-4adc-883f-9bf66128b42b)

I have disabled hot corners, but I notice the bug exists for the sides as well, just half as much. I'm using the default Terminal, I just changed the colours and fonts a bit as I'm an old geezer who used VT102's. :)

I think the second bug may be related, as it has the same "off by one" problem where a single pixel offset will fail to activate the window underneath, but will activate if I click - which is the same behaviour.

My suspicion at the moment is that you are receiving a stream of events from the API, but they're lagged just a bit. So if you're using the last event received as the X,Y co-ord for raising windows, it's off by one.

Another approach could be to receive the event, but then query for the actual X,Y co-ord of the pointer to perform the raise? It would be interesting to know if the event vs current pointer co-ord ever differs.

**Comment by sbmpost** [comment]
@web3d0 

> after a few hours or a laptop sleep, AutoRaise has to be toggled off and on again to make it work

Ah, It seems that is because AutoRaise crashes with the recent changes I made. I have a fix for it however.

If you think the one pixel off bug is related to the corner/edge flick bug, then perhaps the  video you suggested is helpful after all.

Thanks for providing me with so much detail. It helps :-)

**Comment by web3d0** [comment]
First part of the video shows the corner bug still exists, but not as much as before (50ms to 20ms?). Second half of the video shows a window being put over the first window, but with a 2 pixel offset at the bottom. Now mouse to bottom doesn't activate the underlying window until clicked. You can see me moving to the bottom, nothing happens, then I click. I do this twice, so my suspicion is that there is some "around the cursor" or "cursor event lag" where the event itself is reporting an old position and you need to AutoRaise on the current cursor position instead.

https://github.com/sbmpost/AutoRaise/assets/140585/bc007d23-d866-4840-8b17-dcfe356197a4

**Comment by sbmpost** [comment]
@web3d0 

So I spent some more time on these issues. The problem in your last video has to do with MacOS making windows 3 pixels larger than they actually are. This has been documented in AutoRaise.mm like so:

``
// It seems OSX Monterey introduced a transparent 3 pixel border around each window. This
// means that when two windows are visually precisely connected and not overlapping, in
// reality they are. Consequently one has to move the mouse 3 pixels further out of the
// visual area to make the connected window raise. This new OSX 'feature' also introduces
// unwanted raising of windows when visually connected to the top menu bar. To solve this
// we correct the mouse position before determining which window is underneath the mouse.
``

As a workaround, AutoRaise pretends the mouse is moving 3 pixels ahead in the direction you were moving. This works nicely as long as there is space to move in. At the screen border however there is no such space left. So a possible fix for this would be that if the screen really ends (no secondary screen connected at that point), the mouse position is clipped exactly the screen border. I will investigate further if this is easy to implement. This may also fix the problem in the corners of the screen. I will keep you up to date on the progress.

**Comment by sbmpost** [comment]
@web3d0 

It was quite a hassle, but I think the screen edge/corner issues should be solved with the latest code I pushed. I also updated the UI (v4.8.1), so testing it should be quite easy. With these changes, you can revert to polling interval of 50ms which is better for the CPU load. I hope it works properly now. Let me know if it does ;-)

**Comment by web3d0** [comment]
All looks good now! Makes a huge difference to just flick to the window instead of needing to double check! Good one, thanks! :)

**Comment by web3d0** [comment]
100% solved
