### ISSUE TITLE
Focussing full app instead of specific windows

### ISSUE THREAD

**Issue by wsny** [sbmpost/AutoRaise#186]
I'm not sure if the title accurately describes my issue, but the reproduction is pulling out a YouTube video into a picture-in-picture mode out of the browser (Firefox in my case). Mousing over the PiP will focus the browser window as well, which is undesirable in my case. Not sure if there is a way to avoid this built in, or some way to mitigate it?

Attached is window info for the PiP window if that is useful.
![pip_info](https://github.com/sbmpost/AutoRaise/assets/3209815/a1fe2096-0a81-47fb-8224-56c49bc546f1)

**Comment by sbmpost** [comment]
@wsny 

My first thought would be this is a bug in Firefox. If I recall correctly similar behavior was observed in the past with the firefox browser window itself in the past. This is all speculation however so when time allows me to, I will have a look.

**Comment by sbmpost** [comment]
Related: #100

**Comment by wsny** [comment]
Ah, ya turning off the raise part and keeping the focus part I think is more to my liking over all anyway, thanks! I guess feedback on settings is that I was having an issue trying to figure out how those settings were different, but I'm also using AeroSpace tiling window manager, so most of the time windows were not overlapping anyway.
