### ISSUE TITLE
focus and autoraise certain apps only.

### ISSUE THREAD

**Issue by fullstackneo** [sbmpost/AutoRaise#187]
Thank you so much for making this app, it saves tons of useless clicks!

Currently, I am using AutoRaise to focus and raise Chrome and VSCode only. However, they block other apps if I accidently move the cursor out of those apps, I notice I can set "ignore apps" or set "focus app" by finding and typing apps' bundle ids one by one, which resulting in a long list and takes a lot extra setting time for so many other apps. When more apps are added in the future, people have to add them again and again. 

I was still wondering how to ignore all other apps(except Chrome, VSCode), maybe with a regex setting? Are you planning to add it in the furure? :) Thank you very much.

**Comment by fullstackneo** [comment]
looks similar to https://github.com/sbmpost/AutoRaise/issues/176

**Comment by sbmpost** [comment]
@fullstackneo 
Yes it is similar to #176.
You can do a +1 over there. It is on my list of things to do. Meanwhile you can invert the ignore list yourself by adding one exclamation mark and recompiling. You won't have the UI, but at least something workable until this is implemented.

**Comment by fullstackneo** [comment]
Awesome. Thank you very much :)
