### ISSUE TITLE
Mouse warp for same app's windows

### ISSUE THREAD

**Issue by fullstackneo** [sbmpost/AutoRaise#188]
Hello, I have found "Mouse Warp" works when switching app(cmd+tab), not work on different windows of same app(cmd+`). It would be great if it also works for the same app too :) Thank you very much. 

https://github.com/sbmpost/AutoRaise/assets/97574983/5e65ea00-ff7d-4746-84ee-96db807ecedd

Here is my setting
![image](https://github.com/sbmpost/AutoRaise/assets/97574983/13a7bccd-b48f-48a2-a3b4-440ef49058bc)

**Comment by sbmpost** [comment]
@fullstackneo 

That would indeed be a very nice addition. I think it depends on whether the cmd-backtick key combination can be intercepted similar to cmd-tab. Thanks for reporting!

**Comment by sbmpost** [comment]
@fullstackneo 

Implemented in branch [AutoRaise 4.8](https://github.com/sbmpost/AutoRaise/tree/AutoRaise-4.8)

**Comment by fullstackneo** [comment]
Awesome. Thank you!

**Comment by alexnguyennn** [comment]
not sure if it's just me but i've just given version 5.1 a go (with alternative task switcher enabled) and am still seeing that the warp only works when source and destination are different apps (at least in the case of Firefox Developer Edition).

**Comment by sbmpost** [comment]
@alexnguyennn 

Currently the functionality only works without alternative task switcher. However this restriction may not be necessary. Something for AutoRaise 5.2 I suppose ;-)

**Comment by alexnguyennn** [comment]
thanks for the reply; just curious if the reopen and close with 5.2 release means that support for warping between same app windows using the alternative task switcher should be in?
just gave the new release a try and seeing the same behaviour, wondering if it's my config 😅

**Comment by sbmpost** [comment]
@alexnguyennn 

> thanks for the reply; just curious if the reopen and close with 5.2 release means that support for warping between same app windows using the alternative task switcher should be in?

😊 oops, closed this one too soon. Would it be possible to create a new issue for this? This way I won't confuse myself thinking this was already implemented ;-)

**Comment by alexnguyennn** [comment]
> @alexnguyennn
> 
> > thanks for the reply; just curious if the reopen and close with 5.2 release means that support for warping between same app windows using the alternative task switcher should be in?
> 
> 😊 oops, closed this one too soon. Would it be possible to create a new issue for this? This way I won't confuse myself thinking this was already implemented ;-)

certainly - made #208 . thanks in advance!
