### ISSUE TITLE
能否增加一个点击时聚焦外加click功能？

### ISSUE THREAD

**Issue by zhaoaaaaa5** [sbmpost/AutoRaise#194]
如果移动到窗口自动聚焦，有时会隐藏掉小窗口的程序。
程序a全屏，程序b和c在程序a上方，如果鼠标聚焦在程序a上，程序b和c都会隐藏，这个使用用起来好鸡肋，能否在用户点击时选择聚焦吗?
这样可能显得这个程序没有用，但是我真正使用这个程序的用途是看视频或者别的应用需要先聚焦在使用时的场景。

以下是举例说明，网页视频在第一屏幕全屏播放时失焦，用户在第二屏幕上聚焦im聊天，此时如果想在第一屏幕上点击暂停，需要先点击一次聚焦在点击一次才可以暂停，此时就提到了我上面的需求点，如果能让用户只对着失焦视频点击一次即可暂停播放就行。

**Comment by sbmpost** [comment]
如果设置了“focusonly”选项，则漂浮在程序a上方的小程序不应消失。如果这种情况确实发生，就会发生一些奇怪的事情。也许您可以为我录制屏幕并发布？

**Comment by zhaoaaaaa5** [comment]
> @zhaoaaaaa5
> 
> 如果设置了“focusonly”选项，则暂停在程序A上的窗口不会消失。如果发生这种事那就奇怪了。也许您可以为我记录您的屏幕并发布？
> 
> 但是，当你在其下方的窗口上单击鼠标时，浮动窗口总是会消失。macOS就是这么做的，不幸的是这个无法调整。

![image](https://github.com/sbmpost/AutoRaise/assets/17667815/d2f6a1a1-9f15-427d-a17b-fa92860ce56a)

我在mouse warap里面开启了里面的设置后，有所改善，程序a上悬浮的窗口不会消失。不知道是不是你所说的forusonly。

我在实际使用中有个问题是，不想让鼠标移动到对应的窗口进行聚焦，而是和Windows系统一样，鼠标移动到失焦窗口，此时点击失焦窗口的元素，此时失焦窗口在点击时聚焦，同时鼠标指针所对应的失焦窗口上的元素会相对应的执行点击事件，不知可否有这种功能。

可能我的描述有些绕口。同时提出的功能点，可能和本软件的开发主旨有冲突。

**Comment by sbmpost** [comment]
> 我在mouse warap里面开启了里面的设置后，有所改善，程序a上悬浮的窗口不会消失。不知道是不是你所说的forusonly。

“mousewarp”设置使鼠标在通过“cmd-tab”获得焦点时跳转到窗口的中心。所以那是另一回事了。要启用“focusonly”只需禁用“windowraise”，请参见下面的屏幕截图：

![Screenshot 2024-03-26 at 14 51 18](https://github.com/sbmpost/AutoRaise/assets/10278551/67edd4c8-9ee1-499e-a677-d38cb4daf90e)

> 我在实际使用中有个问题是，不想让鼠标移动到对应的窗口进行聚焦，而是和Windows系统一样，鼠标移动到失焦窗口，此时点击失焦窗口的元素，此时失焦窗口在点击时聚焦，同时鼠标指针所对应的失焦窗口上的元素会相对应的执行点击事件，不知可否有这种功能。可能我的描述有些绕口。同时提出的功能点，可能和本软件的开发主旨有冲突。
我认为您建议使用“点击通过”功能：焦点保持在原来的位置，但是当您单击 UI 元素时，您不想单击两次来激活它。

不幸的是，这并不容易实现。因此，提前聚焦窗口是下一个最好的事情（特别是如果您禁用“windowraise”，如上面的屏幕截图所示）。请注意，#9 中也提出了类似的请求。

**Comment by zhaoaaaaa5** [comment]
> > 我在鼠标warap里面打开了里面的设置后，情况有所改善，程序上悬浮的窗口不会消失。不知道是不是你说的仅供我们使用。
> 
> “mousewarp”设置使鼠标在通过“cmd-tab”获得焦点时跳转到窗口的中心。所以那是另一回事了。要实现“focusonly”只需取消“windowraise”，请参见下面的屏幕截图：
> 
> ![截图 2024-03-26 14 51 18](https://private-user-images.githubusercontent.com/10278551/316889178-67edd4c8-9ee1-499e-a677-d38cb4daf90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjMyODMsIm5iZiI6MTcxMTQ2Mjk4MywicGF0aCI6Ii8xMDI3ODU1MS8zMTY4ODkxNzgtNjdlZGQ0YzgtOWVlMS00OTllLWE2NzctZDM4Y2I0ZGFmOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWI1Y2I5NGExMThjYTVlM2ZhY2RlMGFmMTk4YTg1ODc4Yjk3ZmQzMzVmYWRhNjFkY2RjZWI1Y2RjOTRkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hAbm6BVWLXD92bOBSvMnSSCvQRiVoPqhU7t3hUnt7tE)
> 
> > 我在实际使用中有个问题是，不想让鼠标移动到对应的窗口进行焦点，而和Windows系统一样，鼠标移动到失焦窗口，此时点击失焦窗口的元素，此时失焦窗口在点击时焦点，同时鼠标指针所对应的失焦窗口上的元素会相对应的执行点击事件，不知可否有这种功能。可能我的描述有些绕口。同时提出的功能点，可能和本软件的开发主意图有冲突。
> > 我认为建议使用“点击通过”功能：焦点保持在原来的位置，但是当您单击 UI 元素时，您不想单击两次来激活它。
> 
> 不幸的是，这并不容易实现。因此，提前聚焦窗口是下一个最好的事情（特别是如果您取消“windowraise”，如上面的屏幕截图所示）。请注意，#9中也提出了类似的请求。

感谢回答，

> > 我在鼠标warap里面打开里面的设置后，情况有所改善，程序上悬浮的窗口不会消失。不知道是不是你说的我们用的。
> 
> “mousewarp”设置使鼠标在通过“cmd-tab”获得焦点时跳转到窗口的中心。所以那是另一回事了。要实现“focusonly”只需取消“windowraise”，请参见下面的屏幕截图：
> 
> ![截图 2024-03-26 14 51 18](https://private-user-images.githubusercontent.com/10278551/316889178-67edd4c8-9ee1-499e-a677-d38cb4daf90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjMyODMsIm5iZiI6MTcxMTQ2Mjk4MywicGF0aCI6Ii8xMDI3ODU1MS8zMTY4ODkxNzgtNjdlZGQ0YzgtOWVlMS00OTllLWE2NzctZDM4Y2I0ZGFmOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWI1Y2I5NGExMThjYTVlM2ZhY2RlMGFmMTk4YTg1ODc4Yjk3ZmQzMzVmYWRhNjFkY2RjZWI1Y2RjOTRkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hAbm6BVWLXD92bOBSvMnSSCvQRiVoPqhU7t3hUnt7tE)
> 
> > 我在实际使用中有个问题是，不想让鼠标移动到对应的窗口进行焦点，而和Windows系统一样，鼠标移动到失焦窗口，此时点击失焦窗口的元素，此时失焦窗口在点击时间焦点，同时鼠标指针所对应的失焦窗口上的元素会相对应的执行点击事件，不知可否有这种功能。可能我的描述有些绕口。同时提出的功能点，可能和本软件的开发主要目的是有冲突。
> > 我认为建议使用“点击通过”功能：焦点保持在原来的位置，但是当您单击 UI 元素时，您不想单击两次来激活它。
> 
> 不幸的是，这并不容易实现。因此，提前聚焦窗口是下一个最好的事情（特别是如果您取消“windowraise”，如上面的屏幕截图所示）。请注意，#9中也提出了类似的请求。

感谢回答，这个我刚才也试了一下感觉还是差那么一点不够到位。看了下之前的提问，看到有好多和我一样从windows转到mac有同样困扰的人。看来只能当自适应用户了😭。

**Comment by sbmpost** [comment]
Closing this issue because on MacOS it is not trivial to implement click through. Focus first is therefore the next best thing, see also #9
