### ISSUE TITLE
Can't enable/disable auto raise from Alfred Sonoma 14.4.1

### ISSUE THREAD

**Issue by JosefGvirt** [sbmpost/AutoRaise#197]
Hey guys first of all an amazing app kudos! I am running mac os sonoma 14.4.1 (latest) and I tried to bind a apple script for a keyword trigger in alfred and pasted your script in readme page with .app extension at the end of path.

for some reason the script doesnt work after envoking the keyword.

here's the script:
---
on run {input, parameters}
    tell application "Finder"
        if exists of application process "AutoRaise" then
            quit application "/Applications/AutoRaise.app"
            display notification "AutoRaise Stopped"
        else
            launch application "/Applications/AutoRaise.app"
            display notification "AutoRaise Started"
        end if
    end tell
    return input
end run

**Comment by sbmpost** [comment]
@JosefGvirt 

Are you using the precompiled binary from AutoRaise.dmg or compiling AutoRaise.app yourself? The binary inside the dmg is the UI version which allows you to set a keyboard shortcut to enable/disable. The provided AppleScript should also be able to start/stop the UI version, but with the keyboard shortcut option it might be a bit redundant. If however you are compiling AutoRaise.app yourself, and you are using focusFirst = 1 (see your ~/.AutoRaise configuration file), then maybe you haven't provided the EXPERIMENTAL_FOCUS_FIRST flag during compilation. Another caveat is that sometimes on MacOS Accessibility rights seem enabled, whereas in reality this is not the case. To be absolutely sure, in Accessibility settings, find the "AutoRaise" entries and click the minus to get rid of them. Then trigger the script and the entry should reappear. As you can see it can be many things. I also attached a screenshot of how I am testing this myself from within Automator, see below:

![Screenshot 2024-04-02 at 10 07 57](https://github.com/sbmpost/AutoRaise/assets/10278551/faca9f14-cd6e-4e98-bf55-64b023a66afe)

**Comment by sbmpost** [comment]
@JosefGvirt 

I am about to close this issue. I hope the above explanation helps.
