### ISSUE TITLE
Open, Save dialogs flickering

### ISSUE THREAD

**Issue by stuaxocabinetoffice** [sbmpost/AutoRaise#198]
I have AutoRaise set to do Focus Follows Mouse.

In Libre Office Calc, I go to Save-As.
As I move the mouse around MacOS makes a sound and the dialog refreshes.

**Comment by sbmpost** [comment]
@stuaxocabinetoffice 

It would seem other system dialogs suffer from the same problem. Previously such dialogs may not have had a window title and therefore could easily be distinguished from regular "main" windows. I think this may have changed in sonoma. This will require more research though to see how it can be fixed.

**Comment by sbmpost** [comment]
@stuaxocabinetoffice 
It took some research, but I think this is fixed now in master v5.2
