### ISSUE TITLE
Switch on hover

### ISSUE THREAD

**Issue by markNZed** [sbmpost/AutoRaise#2]
I wonder if it could switch on hover i.e. when the mouse is not moving. So it could switch very rapidly if the mouse stops on the window and ignore the mouse is just crossing over a window. Anyway it seem workable as is, thanks.

**Comment by sbmpost** [comment]
If I understand correctly, you would like the window to be raised only if it has not been moving for some time. This is what the code is already doing:

Step 1. The mouse moves: A counter is set to the delay you specified on the command line.
Step 2. The counter starts to count down
Step 3. If the mouse moves before the counter hits zero, we reset it (we are back in step 1)
Step 4. The counter hits zero: The window is raised.

So to prevent the windows you are crossing from being raised, you may want to play a bit with the delay.

**Comment by sbmpost** [comment]
I thought some more about your comment, and figured maybe I can do some extra fine tuning. So I lowered the polling time (this does mean higher cpu usage however). And then default delay is now set to value 2. These settings seem to be quite acceptable and prevent windows being raised when crossing them. You can try for yourself with this version: https://github.com/sbmpost/AutoRaise/blob/fix-issue-1/AutoRaise

**Comment by markNZed** [comment]
Sorry for my slow reply. I tested it and it works well. I like being able to get from a window to the menu bar without having to worry about raising windows in between. Thanks.

**Comment by sbmpost** [comment]
No worries, and thanks for the feedback!
