### ISSUE TITLE
Microsoft Teams won't focus

### ISSUE THREAD

**Issue by pkolano** [sbmpost/AutoRaise#200]
First off, thanks for a great utility!  It makes macs so much more pleasant!  I have v5.1 installed with "old_activation_method" and "experimental_focus_first" and use delay=0 to focus without raise.  For some reason, all apps I've tried seem to work perfect except microsoft teams.  The teams window will not get focus so you have to manually click on it.  I noticed that if you use:

ignoreApps="Microsoft Teams (work or school)"
invertIgnoreApps=true

the window does get focus so it is capable of automatically getting focus, but for some reason doesn't without those settings.  Can you please take a look?  Thanks!

**Comment by sbmpost** [comment]
@pkolano 

Are you sure you had been running AutoRaise 5.1 the first time you tried without the workaround you applied later? The reason I ask is that if a Microsoft Teams window gets filtered out for some reason, the logic for the workaround is skipped. Also when I start Microsoft Teams, the main window with the buttons "sign-in/join a meeting" focusses correctly. Note that the code explicitly filters out Microsoft Teams "meeting" windows because of strange behaviour. See issue #191

**Comment by pkolano** [comment]
yes, pretty sure I've only ever been using 5.1.  It may work ok before you sign in.  Microsoft has both "classic" and "new" teams and if you switch between them, there is a window that comes up initially and that window does focus and unfocus just fine.  Once you log into the main window, however, and it comes up with the main screen with all your chats, then it starts just ignoring the window.  I had looked at that other issue you mentioned, but it seemed to be more about when you have an active meeting going.  In my case, I am not in a meeting, but just in the screen where you do most of the interaction with chats, etc.  Don't know if there is a way to temporarily disable the special teams handling you fixed in the other issue to see if that may be causing the problem.

**Comment by sbmpost** [comment]
@pkolano 

> Don't know if there is a way to temporarily disable the special teams handling you fixed in the other issue to see if that may be causing the problem.

Well, you can start AutoRaise from the commandline with the verbose flag enabled. Then if you move your mouse over the window that isn't focused, AutoRaise should tell you it is being excluded in the terminal log. It should also tell you the title of that window which is what the exclusion is based on. If you can post that log, then I can hopefully create a fix.

**Comment by pkolano** [comment]
It shows:

2024-04-08 21:19:26.746 AutoRaise[55281:3116301] Mouse window: Chat | Paul Kolano (You) | Microsoft Teams
2024-04-08 21:19:26.746 AutoRaise[55281:3116301] Excluding window

So I think perhaps the name is completely dynamic.  It is showing "Chat" because I was currently in the "Chat" tab of teams (I imagine this might also appear as "Activity", "Teams", "Calls", etc.).  It is showing "Paul Kolano (You)" because I was in the "draft chat" area under myself.  This could potentially be anything depending on the names of the people/groups in the chat and likely differs depending on which tab you are on.  For example, when I switch to "Calendar", it shows as:

2024-04-08 21:25:47.516 AutoRaise[55693:3122650] Mouse window: Calendar | Microsoft Teams
2024-04-08 21:25:47.516 AutoRaise[55693:3122650] Excluding window

Probably the only constant is the "| Microsoft Teams" at the end.

**Comment by sbmpost** [comment]
> | Microsoft Teams

Which is exactly the string filtered on. Given that some people want the filter and others not, it should become a setting instead of being hard coded. It has been on my todo list for a while. If you don't want to wait, a temporary solution would maybe be to downgrade to AutoRaise 4.7. Thanks for the details you have given :-)

**Comment by sbmpost** [comment]
@pkolano Should be fixed in latest master (AutoRaise v5.2)

**Comment by pkolano** [comment]
Awesome, thank you!  Works perfect now!
