### ISSUE TITLE
Bug: native dropdown is treated as another app window

### ISSUE THREAD

**Issue by kopach** [sbmpost/AutoRaise#201]
Issue is reproducible in standard macOS Mail app
See recording below. Note, I can't select anything from dropdown

![2024-04-07 12 05 56](https://github.com/sbmpost/AutoRaise/assets/8749624/46fd4ae7-1476-4d41-b6b0-e729d1f24eea)

My config is:
```
delay=0
```

App is installed with `brew install autoraise --with-dexperimental_focus_first`

As temporary workaround for me I've updated config like so

```
delay=0
ignoreApps="Mail"
```

**Comment by sbmpost** [comment]
@kopach 

Thanks for the detailed write-up. I created a fix for this, which hopefully can be included in AutoRaise 5.2

**Comment by sbmpost** [comment]
@kopach 

AutoRaise 5.2 is in master now and contains the fix

**Comment by kopach** [comment]
Thanks, it works as expected. It also solved the issue with “file open” native osx window which was flickering in some cases
