### ISSUE TITLE
Slack window is ignored on MacOS Sonoma

### ISSUE THREAD

**Issue by okolak** [sbmpost/AutoRaise#206]
Slack window is not focused and/or auto raised on MacOS Sonoma.  So far I did not run into this issue with other apps, so it does not seems to be a general problem with may installation/configuration.

I have version 5.2.0, installed from the DMG image.

Focus  (150ms delay) and Raise (0 delay) are both enabled.  Wrap mouse and do not raise on space change are also enabled.  I  tried with different setting configurations as well, no change.

**Comment by sbmpost** [comment]
@okolak 
I can't reproduce this and I am using slack on a daily basis on Sonoma. I remember from the past however that I actually needed to restart my computer when it once failed. It is a long shot, but it might solve your issue.

**Comment by okolak** [comment]
Yep, a reboot fixed it.  I should have tried that before filing the issue.  Thanks for the suggestion.
