### ISSUE TITLE
Mouse warp for windows of the same app when using alternative task switcher doesn't work

### ISSUE THREAD

**Issue by alexnguyennn** [sbmpost/AutoRaise#208]
This is a continuation of [#188](https://github.com/sbmpost/AutoRaise/issues/188) which fixed the situation for default task switcher but not the alternate one.

Situation:
Mouse warp between 2 windows belonging to the same app does not work when `altTaskSwitcher` is enabled.
Say, window A and window B both belonging to app X. Window A is currently focused.

Action: Focus window B -> observe that mouse has not warped or moved despite focus moving to window B.

I'd expect mouse to move to window B after focus has been activated on it.

Note: I'm using [aerospace](https://github.com/nikitabobko/AeroSpace) to change focus of windows which seems to work well with autoraise on windows of different apps.
In case it matters, I also have the MacOS `Displays have separate spaces` setting off.

Example config:

```
delay=0
focusDelay=0
warpX=0.5
warpY=0.5
altTaskSwitcher=true
```

**Comment by sbmpost** [comment]
@alexnguyennn 

Implemented and in master.

**Comment by alexnguyennn** [comment]
thanks for the quick turnaround - just gave it a go and got mixed results. seems some apps like Firefox aren't responding to the cmd-backtick warp while others (I tested Brave works) are. 
it also seems `aerospace` isn't switching focus using the cmd backtick mechanism as I was hoping (focusing with aerospace still only activates warp on windows of different apps) so guess it's an issue with that aerospace itself.

if this is intended behaviour (re: some apps will respond and warp but others don't) happy for this to be closed, thanks again!

**Comment by sbmpost** [comment]
@alexnguyennn 

> it also seems aerospace isn't switching focus using the cmd backtick mechanism as I was hoping

Just to verify if I understand this statement: so even if AutoRaise isn't running, AeroSpace windows do not respond to cmd-backtick. Is this correct? Indeed AutoRaise doesn't implement cmd-backtick itself. It merely intercepts the key combination assuming the focus will change by means of the window manager.

**Comment by sbmpost** [comment]
@alexnguyennn 

I just ran latest Aerospace and Firefox together. If I open two firefox windows and use " option / " to arrange them, I can use cmd-backtick to switch between them and the mouse warps as it should. So you might want to double check your setup.

**Comment by alexnguyennn** [comment]
> @alexnguyennn
> 
> I just ran Aerospace and Firefox. If I open two firefox windows and use " option / " to arrange them on a single screen, I can use cmd-backtick to switch between them and the mouse warps as it should. So you might want to double check your setup.

thanks for the extra data point - gave it another go and found that turning off `sketchybar` allowed `cmd-backtick` manual presses to make the mouse warp to follow focus as intended. However, `aerospace` focus changes themselves to windows of the same still aren't triggering the mouse warp for me - wonder if that's consistent with what you saw too?

**Comment by alexnguyennn** [comment]
> @alexnguyennn
> 
> Implemented and in master. Note this assumes a window of the same app receives focus by means of the cmd-backtick key combination.

think the original spec of the implementation was completed though so closing, making this work with `aerospace` is a separate issue (and gravy at this point)
