### ISSUE TITLE
Proposal: app for macOS

### ISSUE THREAD

**Issue by MDNich** [sbmpost/AutoRaise#21]
I quickly made an app with the provided binary, perhaps you guys could make that one available for download that way it is not terminal-dependent.

https://www.mediafire.com/file/clb12ihiviosho7/AutoRaise.app.zip/file

to check the app for malware, just remove the ".app" and run a diff with the binary in the app and what you provide. Also, the info.plist may require a bit of adjustment for the copyright; I just provided placeholder stuff.

An app icon would be nice too:)

AWESOME SOFTWARE!!!! LOVE IT

**Comment by sbmpost** [comment]
@MDNich nice!

So it seems there is a need for an app version for this, as someone else also did something similar, see:

https://github.com/lhaeger/AutoRaise/pulls

I am ok making this an app, but one of my concerns is that it could bring in unnecessary dependencies (for example if people want to compile this themselves). That being said, wrapping this into an app in the way that you did is possible. It would be nice if this could be done from the command line and made part of the compilation instructions in the README. What do you think?

**Comment by Dimentium** [comment]
>  if people want to compile this themselves

I compiled it last week for Apple Silicon. it works perfect :)

**Comment by sbmpost** [comment]
@Dimentium @MDNich

I have added the possibility to create AutoRaise as an app. You can simply call the "create-app-bundle.sh" script from a bash terminal. Hope this helps ;-)

**Comment by MDNich** [comment]
> @Dimentium @MDNich
> 
> 
> 
> I have added the possibility to create AutoRaise as an app. You can simply call the "create-app-bundle.sh" script from a bash terminal. Hope this helps ;-)
> 
> 
> 
> 
> 
> 

Thank you so much!!! You guys are awesome. Referring this to all my friends!! Maybe you could also put the app for download as well as the script to compile it?
Awesome stuff.

**Comment by sbmpost** [comment]
@MDNich 
> Maybe you could also put the app for download as well as the script to compile it?

The script to compile it is already in the master branch. Providing the app for download is a little useless, as it needs to be code signed for otherwise it won't easily run on people's systems without circumventing Apples security measures. That's why I provided detailed instructions in the README on how to compile the app yourself.

**Comment by sbmpost** [comment]
Closing the issue, @MDNich @Dimentium thank you for reporting!
