### ISSUE TITLE
Version for High Sierra

### ISSUE THREAD

**Issue by abpolly** [sbmpost/AutoRaise#23]
The created app bundle is for macOS 10.14. AutoRaise file is working on macOS 10.13.6 but every time on launch it is necessary to allow the "System Preferences - Security and Privacy - Privacy". Would it be possible to have a version to macOS 10.13.6 High Sierra? AutoRaise is a very useful and practical. Thank you.

**Comment by sbmpost** [comment]
<img width="656" alt="Screenshot 2021-01-22 at 12 10 14 PM" src="https://user-images.githubusercontent.com/10278551/105483922-d99be380-5caa-11eb-9382-2d5ba823578a.png">

@abpolly That is weird. Adding it (see the screenshot) and ticking the checkbox should be sufficient and something you only do once. Note that in my screenshot, I used the AutoRaise app bundle version which has the icon, but it works the same for non bundle version (see the README). I did notice that sometimes it is needed to untick and tick the checkbox of the screenshot to make the setting go through properly. But once it works, it should never ask you again. Maybe you can give me some more details on the steps you are taking?

**Comment by abpolly** [comment]
Hi Stefan,

Thank you for prompt reply. Here are my observations.

- I am using a single file, not a bundle.
- Downloaded file AutoRaise is copied to /Applications
- chmod 700 /Applications/AutoRaise
- Created Automator service with the Applescript you provided
- Assigned a keyboard shortcut to the service
- Created files AutoRaise.delay and AutoRaise.warp

Now there are two ways to launch AutoRaise:
(1) Using keyboard shortcut
(2) Double-click on the file

(1) Launch AutoRaise with keyboard shortcut
- Notification: AutoRaise Started
- Request to allow AutoRaise in the Sys.Preferences-Privacy => Allowed
- AutoRaise is functioning
- Directory created with AutiRaise copied into it:

`/private/var/folders/ts/vlt094tn5px27y99v_yyzg1h0000gn/T/AppTranslocation/CB9E74C1-6A16-40A0-9D29-94CB20D6843D/d/AutoRaise`

- Using keyboard shortcut terminate AutoRaise
- Notification: AutoRaise Stopped
- AutoRaise is disappeared from the Sys.Preferences-Privacy

- On the next launch the sequence repeats including a new directory in

`/private/var/folders/ts/vlt094tn5px27y99v_yyzg1h0000gn/T/AppTranslocation/`

(2) Launch AutoRaise by double-click on the file
-  A Terminal window appears
    `By sbmpost(c) 2021, usage:`
    `AutoRaise -delay <1=20ms> [-warpX <0.5> -warpY <0.5>]`
    `Started with 20 ms delay, warpX: 0.5, warpY: 0.5`
- I need to minimize this Terminal window
- Request to allow Terminal in the Sys.Preferences-Privacy => Allowed
- AutoRaise is functioning
- AutoRaise is terminated by closing this Terminal window.
- The Terminal remains registered with Sys.Preferences-Privacy
- On the next launch by double-click on the file a Terminal window appears
but no need to deal with Sys.Preferences-Privacy

---
So, AutoRaise functioning  close to the intended with the second method.

Hope my description can help.

Thank you,
Alex

**Comment by sbmpost** [comment]
@abpolly very detailed description, thank you! I assume you use an Automator workflow to execute the AppleScript? The fact that it removes the entry from the privacy tab after you stop it via the workflow/keyboard-shortcut is strange. Also that it copies the binary to a temporary folder in this case is strange. Maybe things changed in High Sierra because I am still using Mojave myself. So I suggest for now, you follow the steps I outlined above (the create the app bundle), and see if that is a good workaround. Somewhere this week, I will do some checking with the standalone binary and see if I can reproduce.

**Comment by abpolly** [comment]
Hi Stefan,

- Yes, I used Automator to execute AppleScript.
- I am using macOS High Sierra released before Majave.
- The bundle is for Majave, so I cannot use it.
- I run AutoRaise by double clicking on binary file, then minimizing the
Terminal window.

Thank you,
Alex

**Comment by Dimentium** [comment]
> I run AutoRaise by double clicking on binary file, then minimizing the
Terminal window.

Hi!
May be it would be more comfortable for you to use script like this:

```
#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

pgrep AutoRaise > /dev/null
if [ ! $? -eq 0 ]
then
    /usr/local/bin/AutoRaise -delay 2 -warpX 0.5 -warpY 0.1 &
    disown
else
    pkill AutoRaise
fi
```

I save it with name ``AutoRaiseToggle.sh`` and use for running/stoping.

**Comment by abpolly** [comment]
Hi Stefan,

This is a great solution, elegant and simple!
Thank you so much,
Alex

**Comment by sbmpost** [comment]
@Dimentium @abpolly 
So cool to see people also starting to help each other in using this too haha, nice!
