### ISSUE TITLE
Zoomed windows doesn't raise

### ISSUE THREAD

**Issue by Dimentium** [sbmpost/AutoRaise#24]
Hi,

I don't know - is it bug or feature :)
But zoomed windows doesn't jump up.
There is video: 

https://user-images.githubusercontent.com/5391420/105641079-7bc1f400-5e82-11eb-8339-e7c8d62330da.mov

**Comment by sbmpost** [comment]
A focussed window contained within a larger background window, will keep its focus. This is indeed by design ;-). See here for some additional context: https://github.com/sbmpost/AutoRaise/issues/8#issuecomment-730387978

**Comment by Dimentium** [comment]
> A focussed window contained within a larger background window, will keep its focus. This is indeed by design ;-). See here for some additional context: [#8 (comment)](https://github.com/sbmpost/AutoRaise/issues/8#issuecomment-730387978)

Oh. I see. Thank you!
Is it possible to make this behaviour optional? :)

**Comment by sbmpost** [comment]
It is: you simply change this line of the code:

    needs_raise = window1_id != window2_id &&
        !contained_within((AXUIElementRef) _focusedWindow, _mouseWindow);

into:

    needs_raise = window1_id != window2_id;
    
You might find though that suddenly small dialogs (for example: open file, or add bookmark in chrome), suddenly will disappear when you don't want them to.

**Comment by Dimentium** [comment]
oh.
it make sense.
thank you! )
