### ISSUE TITLE
Putting mouse in Chrome's file-chooser fails to trigger autoraise

### ISSUE THREAD

**Issue by dreeves** [sbmpost/AutoRaise#27]
## Reseminata

1. In Google Chrome, choose "Open File" from the file menu.
2. File-choosing popup modal thing pops up.
3. Move cursor to any other window (another Chrome window or another app, doesn't matter)
4. The other window autoraises fine
5. Move cursor back into file-chooser popup.

## Expectata

Autoraise should happen.

## Resultata

The window from step 3 stays focused and raised. I.e., autoraise fails to happen. (If in step 5 you move the cursor to the window from step 1 but outside the file-chooser popup then autoraise works as expected.)

**Comment by sbmpost** [comment]
@dreeves Can you try with this version?
https://github.com/sbmpost/AutoRaise/blob/2dec4beea657b72648e2a094f22b1bf405d03547/AutoRaise

**Comment by dreeves** [comment]
Alas, the above repro steps reproduce the same bug. I see no difference in behavior with the new binary at all.

**Comment by sbmpost** [comment]
@dreeves 
I was a bit over enthusiastic trying to provide a binary compatible with Mavericks and above. But that didn't really work it seems. [This one](https://github.com/sbmpost/AutoRaise/blob/61db162bd9e9f15883d98134d8b43d136e4d75bf/AutoRaise) should work better.

**Comment by dreeves** [comment]
Fix confirmed! Nice work!
