### ISSUE TITLE
Feature: Decouple autofocus from autoraise

### ISSUE THREAD

**Issue by madchap** [sbmpost/AutoRaise#30]
Hi,

I am a Linux user, using i3 as my [tiling] window manager. I have to use a Mac for work reasons. You cannot image how your small program makes me happy when switching over :-)

I'd have maybe a feature request: would it be possible to have a configuration option to choose whether we want just have the autofocus functionality without the autoraise?

Thank you!

**Comment by dreeves** [comment]
This would be amazing but my understanding is that Apple makes this simply impossible. See @sbmpost's reply to my similar feature request in gissue #7.

**Comment by madchap** [comment]
I see. Well, I am already quite happy as is with this bit of code. Thanks for answering so fast!
