### ISSUE TITLE
Create a homebrew formula

### ISSUE THREAD

**Issue by clintjohnston** [sbmpost/AutoRaise#35]
It would be nice to have a [formula](https://docs.brew.sh/Formula-Cookbook) for the popular homebrew package manager to install & update autoraise, even using a non-core tap.

**Comment by Dimentium** [comment]
@sbmpost 
if you don't have time, you can just create another public repo named "homebrew-autoraise" and somebody (I can try do it) make PR with formula.

```
With URL unspecified, tap a formula repository from GitHub using HTTPS. Since
so many taps are hosted on GitHub, this command is a shortcut for brew tap
user/repo https://github.com/user/homebrew-repo
```

**Comment by sbmpost** [comment]
Another good idea :-) Will try to make this happen, but it will indeed take some time.

**Comment by Dimentium** [comment]
It works, but Im not sure is it OK :)
https://github.com/Dimentium/homebrew-autoraise

**Comment by sbmpost** [comment]
Cool! :-) I will study this a bit somewhere in the coming days

**Comment by sbmpost** [comment]
@Dimentium 
So I had a look, and updated the Makefile to include an install target. Reading through the documentation however, I am not sure if copying the generated app to the /Applications folder is allowed. Or perhaps this should be done using [homebrew-cask](https://github.com/Homebrew/homebrew-cask). Also in their [acceptance criteria](https://docs.brew.sh/Acceptable-Formulae) for homebrew core, they note:

    We frown on authors submitting their own work unless it is very popular.

Not knowing if my tool is popular enough ;-) I suggest we will keep the formula in your repo.

**Comment by Dimentium** [comment]
> I suggest we keep the formula in your repo and you decide to submit it for homebrew core or not.

Ok. No problem.
Thank you! )

**Comment by Dimentium** [comment]
> I am not sure if copying the generated app to the /Applications folder is allowed.

from  [doc](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md):

> Don’t make your formula build an .app (native macOS Application); we don’t want those things in Homebrew. Encourage upstream projects to build and support a .app that can be distributed by homebrew/cask (and used without it, too).

**Comment by sbmpost** [comment]
@Dimentium cool :-)
So I suppose we could update the README to include a link to your formula and close this issue? What do you think?
As a side note, it would seem [lhaeger](https://github.com/lhaeger) made AutoRaise available through [MacPorts](https://ports.macports.org/?search=autoraise) as well.

**Comment by Dimentium** [comment]
@sbmpost it's a great responsibility for me, but I'll do my best )

**Comment by sbmpost** [comment]
@Dimentium I updated the README, so closing this issue.
