### ISSUE TITLE
Some apps, eg BBEdit, don't respond

### ISSUE THREAD

**Issue by prlonsdale** [sbmpost/AutoRaise#40]
some apps, eg BBEdit, don't come into focus when the pointer is moved over their windows.

**Comment by prlonsdale** [comment]
update: mousing over the title bar works, but no other part of the BBEdit window

**Comment by sbmpost** [comment]
@prlonsdale can you try with this [branch](https://github.com/sbmpost/AutoRaise/archive/refs/heads/always-consider-entire-element-hierarchy.zip)

**Comment by prlonsdale** [comment]
yay that works now with BBEdit

**Comment by sbmpost** [comment]
Closed as this is merged into master

**Comment by prlonsdale** [comment]
ah @sbmpost now seeing this again, today with OneNote, which is odd since it worked fine last week with OneNote. don't think OneNote has updated since 21st May
