### ISSUE TITLE
Use mouse cursor 'warp' ONLY

### ISSUE THREAD

**Issue by samwzlim** [sbmpost/AutoRaise#45]
How can I use the 'warp' feature without activating focus follows mouse and autoraise? I would like my mouse cursor to warp to the window when I cmd + tab but do not want the functionality of focus follows mouse and autoraise. Is this possible?

**Comment by sbmpost** [comment]
Not currently possible but there is an easy way to get this anyway. You'd simply have to put a comment symbol // where the call to "onTick" is made in the AutoRaise.mm file:

// cppClass->onTick

Then recompile as explained in the readme. I will consider making this configurable with "-delay -1" or something like that. Thanks for reporting and let me know if the above workaround works for you ;-)

**Comment by samwzlim** [comment]
> Not currently possible but there is an easy way to get this anyway. You'd simply have to put a comment symbol // where the call to "onTick" is made in the AutoRaise.mm file:
> 
> // cppClass->onTick
> 
> Then recompile as explained in the readme. I will consider making this configurable with "-delay -1" or something like that. Thanks for reporting and let me know if the above workaround works for you ;-)

@sbmpost  Hi, so far it's working as long as I run the command in terminal, but when I try to follow the steps to get AutoRaise.app up and running, it opens but nothing happens. The exact step that I'm stuck in is here: 

<img width="845" alt="CleanShot 2021-07-10 at 23 45 56@2x" src="https://user-images.githubusercontent.com/74489037/125168633-03a17d80-e1d9-11eb-9edc-11ad00a478fd.png">

I've managed to create a hidden directory ".AutoRaise", but have no idea how to go about creating the config file. Can you guide me on this? I would really appreciate it :)

**Comment by sbmpost** [comment]
Ah! It should be a hidden file called .Autoraise, not a directory. I see how the instructions are a bit unclear in this regard. So what you can do is:

1. rmdir .AutoRaise
2. nano .AutoRaise
3. Add the configuration
4. CTRL-X to save and exit nano

**Comment by samwzlim** [comment]
> Ah! It should be a hidden file called .Autoraise, not a directory. I see how the instructions are a bit unclear in this regard. So what you can do is:
> 
> 1. rmdir .AutoRaise
> 2. nano .AutoRaise
> 3. Add the configuration
> 4. CTRL-X to save and exit nano

Thanks! It works well :) However, I use multiple users on my mac and can only access Autoraise.app on one user (the one I ran the commands on). On other users, I'm unable to open the app, and it shows this:

<img width="1004" alt="CleanShot 2021-07-13 at 12 34 01@2x" src="https://user-images.githubusercontent.com/74489037/125391389-05389480-e3d7-11eb-8fae-f293ea9cca68.png">

Do you know what I should do to circumvent this? Once again, thanks for your help!

**Comment by sbmpost** [comment]
This can be several things as noted here:

https://stackoverflow.com/questions/64842819/cant-run-app-because-of-permission-in-big-sur/64895860#64895860

I guess you can try these commands from the terminal:

    sudo xattr -dr com.apple.quarantine /Applications/AutoRaise.app
    sudo chmod 755 /Applications/AutoRaise.app

**Comment by sbmpost** [comment]
@samwzlim Hi there!

I added the "warp only" functionality to the master branch and also made sure the produced app can be run by multiple users (applying the 755 described below). So all you have to do is check out the master branch, recompile and "make install" as per the instructions in the README. And to specify you want "warp only", simply set delay=0

**Comment by samwzlim** [comment]
@sbmpost Thank you so much! Everything is now working as expected!

**Comment by sbmpost** [comment]
@samwzlim cool that this is working as expected and thanks for reporting! :)

**Comment by samwzlim** [comment]
Re-opening this issue because I work with the mac app 'Contexts' and I thought I would be able to warp the mouse cursor to the application launched by Contexts, just like with cmd + tab, but that isn't the case. Please refer to the gif attached for a comparison between using Contexts and cmd + tab.
![CleanShot 2021-07-23 at 10 13 43](https://user-images.githubusercontent.com/74489037/126730212-30d3908a-c444-4643-b1c0-3a7126551f72.gif)
