### ISSUE TITLE
Change focus only when on different monitors

### ISSUE THREAD

**Issue by hasantahir** [sbmpost/AutoRaise#48]
Hi,

First, thank you for developing this very useful app. I am wondering if it's possible to only switch the focus when the cursor is on different monitors. If two apps are on the same desktop/monitor, the focus should not change.

Thanks.

**Comment by sbmpost** [comment]
@hasantahir 
Officially not, however there is issue #11 for which I created a pull request. So if you see the conversation over there, you can see how to compile a version that only changes the focus when changing screens. At some point I will include this functionality in the master branch but I couldn't find the time for it yet. You reporting this serves as a good reminder to make it happen so thanks for that :-)

**Comment by hasantahir** [comment]
Thanks, @sbmpost for your response. I am going to post a screengrab in the other thread which might be helpful.

**Comment by sbmpost** [comment]
@hasantahir 
I am closing this issue so we can keep track of its progress in the other one (#11).
