### ISSUE TITLE
Fixing macOS window state oversight in full screen apps

### ISSUE THREAD

**Issue by minimum91** [sbmpost/AutoRaise#53]
Hi,

This is not a bug report, but an idea.

I found that in many apps while in fullscreen, for example on two monitors or even split screen on a single monitor - active/inactive window state loses it's purpose and is almost invisible to the user. Right now I have two Microsoft Edge windows open in split screen and there is literally not a single way of identifying which is frontmost and therefore which has keyboard focus (switching between tabs with keyboard etc). I run AutoRaise to mitigate this. This is done by a Keyboard Maestro variable that looks for the fullscreen status via a menu item - as soon as KM identifies the the status as being full screen, it turns on AutoRaise. Switching to any app that is not full screen, AutoRaise is turned off.
This way, when in non-full screen (as originally designed) the user is in control of which window is frontmost by clicking because it is visible and identifiable. When the window(s) is/are full screen and window focus is non-identifiable AutoRaise handles the focus.
I hope it makes sense and gives an idea for a feature. A built in feature for this would be great because via Keyboard maestro there is a considerable delay between the activation and quitting of AutoRaise.

**Comment by sbmpost** [comment]
In summary: an option that would allow you to only raise full screen windows. Interesting thought :)

Most people probably use AutoRaise in exactly the opposite way: they would want it enabled for everything that is not full screen. So your use case seems quite unique. I suppose it is not that difficult to see what state a window is in before to raise it. Let me experiment a bit with that in a separate branch.
