### ISSUE TITLE
Suggestion: set a different delay for a window on another screen

### ISSUE THREAD

**Issue by Smons** [sbmpost/AutoRaise#54]
Hi,

I do not have much use of AutoRaise as it is now (maybe I have misconfigured it?). However, one feature I would really like is the activation of a window when my mouse moves to another screen.

I use 2 screens: my main iMac screen for most of the work and a second monitor for "supporting material". As such, I often have some applications on one screen and other applications on the other one, and I often need to copy/paste some contents between those applications on different monitors.

In such a scenario, I would love AutoRaise to automatically activate an application but only when the mouse goes to another monitor. In order to keep AutoRaise compatible with its current behaviour, I suggest creating a new delay setting for when the mouse pointer goes to a different screen, so that wouldn't change AutoRaise's current behaviour on a single screen.

**Comment by sbmpost** [comment]
Similar requests have been made. See issue #11

I suggest you try with https://github.com/sbmpost/AutoRaise/archive/refs/heads/raise-only-on-change-screen.zip

And see if this meets your needs.
