### ISSUE TITLE
When using autoraise.app where do I create the config file?

### ISSUE THREAD

**Issue by BenJackGill** [sbmpost/AutoRaise#55]
These are the steps I have done:

1. I downloaded the master branch
2. Unzipped it inside my downloads folder
3. Ran `cd ~/AutoRaise-master && make clean && make`
4. Moved `autoraise.app` to the applications folder
5. Deleted the remaining files in the downloads folder since I was not using them (was this correct?)

After all that the app works fine.

But now I want to setup a configuration file as per the Readme, and I don't know where to place that file.

The `autoraise.app` application I moved from the downloads folder to the applications folder was just a single file. So I don't know how to create a configuration file "inside" of that.

**Comment by sbmpost** [comment]
You can create it as follows with nano (mini editor)

1. Open a terminal
2. cd $HOME
3. mkdir -p .config/AutoRaise
4. nano .config/AutoRaise/config
5. add your configuration
6. CTRL-X to save and exit
