### ISSUE TITLE
Doesn't raise emacs (mostly)

### ISSUE THREAD

**Issue by rvandegrift** [sbmpost/AutoRaise#57]
Thanks very much for this software!

I've run into one problem - emacs windows aren't raised on mouse over.  Strangely, even mousing over the window title bar doesn't work.  Well, with one exception - if the emacs toolbar is enabled, mousing over that *does* raise.

I've installed emacs from homebrew: `brew install emacs`.

**Comment by Dimentium** [comment]
hmm. 
I have emacs, but I cannot reproduce this  issue.
I use this:
```
~ 
❯ brew info emacs-plus@27
d12frosted/emacs-plus/emacs-plus@27: stable 27.2, HEAD
/opt/homebrew/Cellar/emacs-plus@27/27.2 (4,018 files, 131.5MB) *
  Built from source on 2021-06-01 at 22:24:04
From: https://github.com/d12frosted/homebrew-emacs-plus/blob/HEAD/Formula/emacs-plus@27.rb
```

I don't remember anymore, but I may have had a similar issue with an qt5 application last year.

**Comment by sbmpost** [comment]
@rvandegrift 
I installed emacs via brew as you explained, but this gives me only the terminal version.
Instead, downloading from https://emacsformacos.com/ gives me the windowed version.
With that particular version I am indeed seeing the behaviour you describe. It will take
some investigation to see if this is due to the application itself, or some corner case in
AutoRaise. I will have a look, but it might take some time.

**Comment by sbmpost** [comment]
@rvandegrift ok, this went faster then I thought. You can download the zipped branch with a fix from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/fix-issue-57-emacs-not-raising.zip)

Don't forget to kill the previous instance you might be running. Then recompile and install according to the instructions in the README.

**Comment by rvandegrift** [comment]
@sbmpost thanks for the quick fix - I can confirm works now, with a quirk.  The emacs windows raise immediately, without respecting my delay.  Other windows continue to delay normally.  The emacs-plus repo that @Dimentium mentioned behaves normally.

Sorry for the confusion about which emacs - I forgot `brew install --cask emacs` isn't the same as `brew install emacs`!

**Comment by mhofert** [comment]
I can confirm this behavior on macOS 12.1 with Emacs 27.2 installed from https://emacsformacosx.com. The new behavior is to immediately raise the Emacs window, but have the desired delay (I use the default delay) for switching to other applications.

**Comment by sbmpost** [comment]
@mhofert
Perhaps you are running two instances of AutoRaise at the same time. One without delay on the background, and one from the terminal with the delay specified. To rule out this possibility, can you can check with:

    ps -A | grep AutoRaise | grep -v "grep"

The output should show at most one instance running. If not, then quit the others with "Activity Monitor".

@rvandegrift @mhofert 
In the meantime I will have a look at the emacs specific behaviour which might be another issue.

**Comment by sbmpost** [comment]
@rvandegrift @mhofert 
I just made the necessary fixes to make this work with Emacs (and probably also other X based applications). The delay setting should also be respected now. To test this, simply download this branch again from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/fix-issue-57-emacs-not-raising.zip). If you can let me know this works correctly now, then I can merge this with master.

**Comment by rvandegrift** [comment]
@sbmpost confirmed, works great!

**Comment by sbmpost** [comment]
@rvandegrift merged :-)
