### ISSUE TITLE
Unistall/Remove AutoRaise

### ISSUE THREAD

**Issue by leonbubova** [sbmpost/AutoRaise#60]
Hey,
I removed the AutoRaise file but it still starts, after every reboot. Surely there must be a way to completely remove it, that I am missin right?

**Comment by sbmpost** [comment]
Not sure how you installed it then. This tool never starts on its own. Additional steps are required to make that happen, which is not part of the README installation instructions. That being said, you might have a look at System Preferences | Users & Groups | Login items, and see if AutoRaise is enlisted there as a startup item. If so, simply remove it.

**Comment by leonbubova** [comment]
Sorry for taking so long to reply and thanks for reminding me of how I actually installed the application :D

I actually used the homebrew install path, so I just had to stop the service there and remove it from homebrew.

Thanks for your help <3
