### ISSUE TITLE
Warp not working on System Preferences

### ISSUE THREAD

**Issue by strobelight** [sbmpost/AutoRaise#61]
The mouse cursor isn't on top of the system preferences window Apple -> Systems Preferences. Does warp only work with command-tab?

**Comment by sbmpost** [comment]
Warp works when you use command-tab to switch to windows. If that happens to be the system preferences window, it should work. Note that if you use a different way to switch apps/windows, you might want to compile the binary using the ALTERNATIVE_TASK_SWITCHER flag. This is further explained in the README.

**Comment by sbmpost** [comment]
@strobelight 
I am closing this issue because I am not able to reproduce it.
