### ISSUE TITLE
Prevent focus change when keyboard viewer used

### ISSUE THREAD

**Issue by strobelight** [sbmpost/AutoRaise#62]
AutoRaise has to be off so that characters entered via the keyboard viewer go into the focused window (instead of focus changing to the keyboard viewer).

**Comment by sbmpost** [comment]
@strobelight
So if I understand correctly, you mean that to Keyboard viewer app should not be autoraised. I never used it but perhaps you indeed do want to exclude certain apps from being raised. Will give this some thought. I do want to mention time is harder to find these days. So it might take a while.

**Comment by sbmpost** [comment]
@strobelight 
I have created a branch that implements this. Can you check if it works for you? To do so, simply download the zip from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/exclude-keyboard-viewer-from-raise.zip) and recompile. Also make sure to stop any previous AutoRaise instances (check with "Activitity Monitor").

**Comment by sbmpost** [comment]
@strobelight 
I am closing this issue as PR #63 has been merged to master
