### ISSUE TITLE
Compatibility with Keyboard Maestro?

### ISSUE THREAD

**Issue by macintacos** [sbmpost/AutoRaise#64]
Hello!

I have a lot of keybindings set up in Keyboard Maestro that allow me to hit a given key combination to bring an application to the foreground. So, let's say for example, I hit "cmd+opt+shift+s" and that brings Slack to the foreground.

I only recently started using AutoRaise, and was hoping that the "warp" feature would work with this method of activating an application, but alas, it does not. Is there any way to get this to work? Ideally I think that the warp feature would have an additional option (or a separate option entirely) that basically says "anytime that a window takes focus (outside of the mouse being the one to activate that application), move the mouse to that window".

Is this possible and I just don't have the application configured properly?

**Comment by sbmpost** [comment]
@macintacos 
Check out the ALTERNATIVE_TASK_SWITCHER compiler option (see the README). I think that answers your need. If not, let me know. And if it does, I also would like to know ;-)

**Comment by macintacos** [comment]
Ah, I hadn't realized that (I'm installing using the homebrew tap). If this works, I'll ask the maintainer there to also see if they can provide a binary that has this compiler option turned on when the binary is built!

**Comment by macintacos** [comment]
Okay great, that works! Sorry for the hassle!

**Comment by sbmpost** [comment]
@macintacos 
No problem and thanks for confirming.
