### ISSUE TITLE
Only one Chrome window is ever autoraised

### ISSUE THREAD

**Issue by dreeves** [sbmpost/AutoRaise#66]
I just got a new M1 Mac and installed AutoRaise via Homebrew.

I'm seeing the following regression from the old version I had on my old Mac:

## Replicata

1. Install AutoRaise via Homebrew
2. Open multiple Chrome windows
3. Move the mouse over some other application
4. Move the mouse to a different Chrome window

## Expectata

That the Chome window that the mouse is on gets focus (aka focus follows mouse).

## Resultata

Just one Chrome window ever gets focus.

---

This is pretty high severity for me, and I can't go back to the old binary I was using since it's not compatible with an M1 Mac.

**Comment by sbmpost** [comment]
@dreeves 
Do you also have a new OSX version now? I never tested AutoRaise on an M1. But I would not suspect it to depend on the architecture of the system. In this case I suppose verbose logging in a terminal might give some clues (see the README how to enable it).

**Comment by dreeves** [comment]
> Do you also have a new OSX version now?

I recently upgraded to macOS Monterey on my old MacBook and that did not break AutoRaise there. So, no, that doesn't seem to be the difference.

But, UPDATE: I think the problem was that I hadn't given iTerm.app accessibility permission yet. Weird that that was only a problem for Chrome auto-raising. In any case, my problem has fixed itself! Thanks so much!

**Comment by sbmpost** [comment]
@dreeves no problem. I am closing this issue then ok?
