### ISSUE TITLE
NSBundle.h:91:143: error: function does not return NSString

### ISSUE THREAD

**Issue by bhodgens** [sbmpost/AutoRaise#69]
This might be due to some unmet requirement - I'm running BigSur 11.6.2 at the moment - but I thought I'd mention it here in the event someone else hits this. 

`bhodgens@cloudbook:AutoRaise$ make install
g++ -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit
In file included from AutoRaise.mm:25:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                         ~~~~~~~~~~~~~~                                                                       ^                  ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~
1 error generated.`

Any help is, of course, appreciated, though I'll be upgrading soon and I'd suspect that would fix things.

**Comment by sbmpost** [comment]
@bhodgens

Could be related to latest Xcode which comes with updated framework. Did you find a workaround? I am reading about a possible workaround [here](https://youtrack.jetbrains.com/issue/KT-48807). I can't test it myself as I am running OSX Monterey for a while now.

**Comment by bhodgens** [comment]
@sbmpost thank you for the response! 

I believe I'm doing this correctly, but - 

```
bhodgens@cloudbook:AutoRaise$ make CXXFLAGS=-DNS_FORMAT_ARGUMENT
g++ -DNS_FORMAT_ARGUMENT -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit
In file included from AutoRaise.mm:25:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:90:122: error: expected ';' after method prototype
- (NSString *)localizedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1);
                                                                                                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:142: error: expected ';' after method prototype
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                                                                                                             ^
2 errors generated.
make: *** [AutoRaise] Error 1
```

**Comment by sbmpost** [comment]
I think the flag should be:
    -D"DNS_FORMAT_ARGUMENT(A)="

**Comment by bhodgens** [comment]
That doesn't appear to work. 
```

bhodgens@cloudbook:AutoRaise$ make CXXFLAGS=-D"NS_FORMAT_ARGUMENT(A)="
g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit'
make: *** [AutoRaise] Error 2
bhodgens@cloudbook:AutoRaise$ make CXXFLAGS="-DNS_FORMAT_ARGUMENT(A)="
g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit'
make: *** [AutoRaise] Error 2
bhodgens@cloudbook:AutoRaise$ make CXXFLAGS=-"DNS_FORMAT_ARGUMENT(A)="
g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `g++ -DNS_FORMAT_ARGUMENT(A)= -O2 -Wall -fobjc-arc -o AutoRaise AutoRaise.mm -framework AppKit'
make: *** [AutoRaise] Error 2
```

**Comment by sbmpost** [comment]
@bhodgens 
Ok, Thanks for testing this. I suppose I can compile myself with the flag on OSX Monterey and see what happens. I will get back to you ASAP.

**Comment by sbmpost** [comment]
@bhodgens
Ok, I just compiled like so:

make CXXFLAGS=-D"NS_FORMAT_ARGUMENT\(A\)="

Note the backslashes before the parenthesis. Does this work on Big Sur for you?

**Comment by bhodgens** [comment]
@sbmpost Stefan, thank you, yes - that builds on Big Sur.

**Comment by bhodgens** [comment]
@sbmpost so fantastic to finally have focus-follows-mouse on OSX.

**Comment by sbmpost** [comment]
@bhodgens Thank you for confirming the fix :-)

> so fantastic to finally have focus-follows-mouse on OSX.

You might be interested in the discussion [here](https://github.com/sbmpost/AutoRaise/issues/47) as well ;-)
