### ISSUE TITLE
Make it work with Bartender

### ISSUE THREAD

**Issue by sbmpost** [sbmpost/AutoRaise#77]
The bartender menu bar below the osx menu bar disappears before you can reach its icons.
Further explanation is [here](https://dev.to/brisbanewebdeveloper/avoid-autoraise-to-activate-the-window-while-pressing-down-the-command-key-305h)

**Comment by sbmpost** [comment]
@brisbanewebdeveloper

FYI

**Comment by sbmpost** [comment]
@brisbanewebdeveloper 
I see what you mean. For this particular case I would probably use another Monitor C for Window B.
Then again your command key solution works as well.

**Comment by sbmpost** [comment]
@brisbanewebdeveloper 
Closing this issue as my changed have been merged to master. See also my previous message about the EXPERIMENTAL_FOCUS_FIRST flag. Thanks for reporting!!

**Comment by brisbanewebdeveloper** [comment]
@sbmpost 

I tried the flag `EXPERIMENTAL_FOCUS_FIRST` with `origin/master`, and got some deprecation messages with `SameProcess()` etc.

I don't code for macOS, but I perceived some functions are no longer good to use for the recent macOS environment (My MacBook is with M1 Processor and it uses macOS Version `12.4`)....?

Just letting you know.

**Comment by sbmpost** [comment]
@brisbanewebdeveloper 
Hi there. There was another user requesting to suppress the focus/raise when holding a certain hotkey. So I probably include your addition in the next release (v3.4). The development branch is [here](https://github.com/sbmpost/AutoRaise/tree/issue-94-various-improvements)
