### ISSUE TITLE
Cursor jump issue for EXPERIMENTAL_FOCUS_FIRST

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#83]
I am noticing that the cursor jump behavior after focusing to an application with Cmd+Tab stops working after some period of daily use. The only way to fix this is to run `brew services restart autoraise`. Am I the only one noticing this bug?

**Comment by sbmpost** [comment]
@samholmes 
So I ran AutoRaise myself for a couple of days, and experienced the same problem. I pushed [this branch](https://github.com/sbmpost/AutoRaise/tree/83-fix-event-tap-disabled) which hopefully fixes this.

**Comment by samholmes** [comment]
@samholmes I'm not familiar with pull down the branch to test from a homebrew install. How do I go about checking out this branch and running it using `brew`?

**Comment by samholmes** [comment]
@sbmpost  I don't know what is the usual way. Is it _not_ to use brew? It looks like https://github.com/Dimentium/homebrew-autoraise doesn't include the commit on master that you mention fixed the issue. The branch you shown shows a commit that isn't on master for the main repo (https://github.com/sbmpost/AutoRaise). I'm just confused on what is the correct way to install updates brew or otherwise?

**Comment by samholmes** [comment]
I cloned the repo, and ran `make clean && make CXXFLAGS="-DEXPERIMENTAL_FOCUS_FIRST"` to build the app. Then I removed the brew service using `brew uninstall autoraise`. Things seem to be working well now with the cursor warp. If the cursor warp fails after awhile, then I'll write another comment.
