### ISSUE TITLE
Mac mini m1 & Monterey 12.4 does not install

### ISSUE THREAD

**Issue by ivokostov** [sbmpost/AutoRaise#84]
> apple@Apples-Mac-mini ~ % cd ~/AutoRaise-master && make clean && make
> 
> rm -f AutoRaise
> rm -rf AutoRaise.app
> g++ -O2 -Wall -fobjc-arc -D"NS_FORMAT_ARGUMENT(A)=" -D"SKYLIGHT_AVAILABLE=1" -o AutoRaise AutoRaise.mm > -framework AppKit -F /System/Library/PrivateFrameworks -framework SkyLight
> ./create-app-bundle.sh
> Successfully created AutoRaise.app
> apple@Apples-Mac-mini AutoRaise-master %

 

**Successfully created AutoRaise.app** but there is no app like AutoRaise

**Comment by sbmpost** [comment]
@ivokostov 
Strange. Have you also tried a "make install" after?

**Comment by ivokostov** [comment]
This work, thank you!
Great app!
