### ISSUE TITLE
Feature Request: Tap to Raise

### ISSUE THREAD

**Issue by samholmes** [sbmpost/AutoRaise#88]
For EXPERIMENTAL_FOCUS_FIRST, you can enable a mode where the cursor will cause a focus the window underneath the cursor. However, there is no way to bring the window to front without clicking within the window. Clicking within a focused window interacts with the window's UI, but clicking on a non-focused window will just bring it to focus and to the front (macOS default behavior). With EXPERIMENTAL_FOCUS_FIRST enabled, there is no way to just bring the window to the front without interacting with the window. I propose a possible solution: Tap to Raise (bring to front). Is it possible to detect a tap on the trackpad (not a click) and have that configured to bring the window to the front? If so, this feature would complete the ideal power-user, UX I could imagine.

**Comment by sbmpost** [comment]
@samholmes 
I have implemented this feature. It is still experimental, but seems to work fine so far.
It also includes the fix for issue #87. To try it out, download from [here](https://github.com/sbmpost/AutoRaise/archive/refs/heads/trackpad-tap-to-raise-feature.zip) and follow the
instruction in the README.

**Comment by samholmes** [comment]
@sbmpost I have a local copy of this repository. Which branch should I check out and which commands should I run to get the desired installation results? I'd like to use the repo to easily switch to main branch once these features/fixes are tracked there. 

The mode I'm looking for is to have `EXPERIMENTAL_FOCUS_FIRST` enabled with tap to bring to front. My config file includes:

```
delay=0
mouseStop=true
```

**Comment by sbmpost** [comment]
First do:

    git checkout trackpad-tap-to-raise-feature
    make clean && make CXXFLAGS="-DEXPERIMENTAL_FOCUS_FIRST"
    ./AutoRaise -delay 0

And if the command line version works you can consider making the app bundle version.

**Comment by samholmes** [comment]
> @samholmes
> 
> > I'd like to use the repo to easily switch to main branch once these features/fixes are tracked there.
> 
> ```
> git checkout trackpad-tap-to-raise-feature
> make clean && make CXXFLAGS="-DEXPERIMENTAL_FOCUS_FIRST"
> ./AutoRaise -delay 0 -mouseStop true
> ```
> 
> And if the command line version works you can consider making the app bundle version.

I tried the exact commands (after you're edits to the GH comment; which include the mouseStop), and I am noticing the mouseStop doesn't work:

```
./AutoRaise -delay 0 -mouseStop true                    

v3.3 by sbmpost(c) 2022, usage:

AutoRaise
  -delay <0=no-raise, 1=no-delay, 2=50ms, 3=100ms, ...>
  -warpX <0.5> -warpY <0.5> -scale <2.0>
  -mouseStop <true|false>
  -verbose <true|false>

Started with:
  * warp and focus only (no-raise)
  * warpX: 0.5, warpY: 0.5, scale: 2.0
  * mouseStop: true
  * verbose: false

Compiled with:
  * EXPERIMENTAL_FOCUS_FIRST
```

The behavior is as though the mouseStop does nothing. The delay 0 means I see instant changes. Perhaps the gesture detection is interfering with regular mouse movement.

**Comment by sbmpost** [comment]
Running it like this on my own machine, mouseStop works perfectly. The only thing I can think of is that there is still an old AutoRaise instance running. To check quickly on the commandline you can use:

    ps -A | grep AutoRaise | grep -v "grep"

It should return nothing. If I recall correctly, you are using a brew formula to install the latest master? Could that still leave its traces somehow?

**Comment by samholmes** [comment]
I'm no longer using brew.

```
~
❯ brew list | grep autoraise

~
❯ 
```

After running he build:

```
~
❯ ps -A | grep AutoRaise | grep -v "grep"

68974 ttys022    0:00.34 ./AutoRaise -delay 0 -mouseStop true
```

Looks like only the built version is running. I notice the first run, mouseStop works fine, but the tap feature doesn't work. If I close the CLI processes and re-run, the mouseStop no longer works. I have to remove the permission from System Preferences and then restart the CLI to get mouseStop to work again. Nonetheless, I haven't been able to get the tap feature to work quite at all yet.

**Comment by sbmpost** [comment]
>  I have to remove the permission from System Preferences and then restart the CLI to get mouseStop to work again.

This is strange. Perhaps I should upgrade to Monterey 12.4 (I am currently on Monterey 12.3.1).
I have seen another user having strange issues as well (see #91). It might be related somehow.

**Comment by sbmpost** [comment]
@samholmes 
I have upgraded and found everything to still work as expected, including mouseStop and the tap to raise feature. So I am not entirely sure what should be the conclusion. So I *think*, you got v3.3 to work properly (struggling with Apples Accessibility, don't worry I am struggling with it too), but tap to raise simply doesn't work for you for some reason.

The only thing left I can think of is a description of the *exact* steps I am taking on my machine:

1) Ensure that no AutoRaise is running:

    ps -A | grep "AutoRaise" | grep -v "grep"

2) I remove the AutoRaise.app item from System Preferences | Security & Privacy | Privacy | Accessibility. 
Note that I remove the item *completely* by clicking the minus.

3) I do the same for the Terminal.app item removing it *completely* by clicking the minus.

4) I download the [zipped version](https://github.com/sbmpost/AutoRaise/archive/refs/heads/trackpad-tap-to-raise-feature.zip) of the "trackpad-tap-to-raise-feature" branch. 
In this way I will be *absolutely* sure that what is on github is also what I get on my own machine.

5) Unzip everything:

    cd ~/Downloads && unzip AutoRaise-trackpad-tap-to-raise-feature.zip

6) Make everything:

    cd AutoRaise-trackpad-tap-to-raise-feature && make clean && make CXXFLAGS="-DEXPERIMENTAL_FOCUS_FIRST"

7) Trying first the command line version:

    ./AutoRaise -delay 0 -mouseStop true

8) OSX should ask you for Accessibility Access for Terminal.app:

<img width="461" alt="Screenshot 2022-07-08 at 10 19 13" src="https://user-images.githubusercontent.com/10278551/177949309-2c7e03d4-c63b-4c92-b499-27ed19382aaf.png">

9) From the dialog, I choose to Open System Preferences.

10) I click the "Unlock" icon, type in my administrator password, and tick the checkbox in front of the Terminal.app item.

11) Next I check if:

- AutoRaise **v3.3** is still running in the terminal.
- MouseStop works correctly

---

So far so good... Now I proceed with checking tap to raise functionality:

11) I check System Preferences | Trackpad settings

![Screenshot 2022-07-08 at 10 10 03](https://user-images.githubusercontent.com/10278551/177947752-4397868c-8403-429c-833f-dcbad96b15a7.png)

12) "Tap to click" and "Secondary click" should both be off

13) Finally, I bring up two windows slightly overlapping each other. I tap very light on the trackpad with the mouse hovering over the yellow minimize button of the bottom window. I expect the bottom window window to raise, but not to be minimized.

**Comment by samholmes** [comment]
I followed the steps stringently. Same issues.

I am using a Macbook Pro trackpad. I'm not sure what you mean by the external mouse. I think if the app could detect a tap gesture on a trackpad (external or otherwise), much like how you can enable tap-to-click on macOS, then it could enable a tap-to-raise feature.

**Comment by sbmpost** [comment]
@samholmes 
The problem is that it is far from trivial to distinguish a tap on the trackpad from moving the mouse on the trackpad. One would expect the tap to be a simple event from the OS, but as always, Apple likes to hide these events from us, making them only accessible through private API's. So the next best I can do is detect a trackpad touch. Unfortunately this is not sufficient because a mouse move is also a touch. I also played with the idea to use the middle mouse button instead (with an external mouse). Unfortunately the middle mouse button suffers from clicking through similar to regular mouse click.

**Comment by samholmes** [comment]
After attempts to use the alternative branch and switching back to a build from master branch, I cannot seem to get cursor warp to work again. I tried:

1. Kill the app completely (using killall or activity monitor)
2. Remove AutoRaise from system security settings
3. `make clean && make CXXFLAGS="-DEXPERIMENTAL_FOCUS_FIRST" && make install`
4. Open AutoRaise.app from Applications dir
5. Enable security setting for AutoRaise
6. Kill app and restart it

Everything is working aside from cursor warp. I wonder if a system restart is all that is needed (I'd rather not restart my system quite yet, but I'll let you know if that fixes it). I'm curious as to what causes cursor warp to break at times?

**Comment by sbmpost** [comment]
@samholmes 
> Looks like I need to add warpX=0.5 and warpY=0.5 to my ~/.config/AutoRaise/config file. That fixed it.

Correct. With version 3.2 there actually was no way to disable warp which was a bug. V3.3 fixed that together with vertical monitor setup.
