### ISSUE TITLE
"separation" of tracking between browsers tab

### ISSUE THREAD

**Issue by GlibMartynenko** [sbmpost/AutoRaise#89]
Hi,
Firstly thank you SO MUCH for all your efforts guys!!!

I have one question.
As for now, when I have two monitors and I've opened Chrome.
On monitor 1 - I have opened the Chrome tab
On monitor 2 - I have opened the Chrome tab.
What if I want to keep the focus on motor 1 and on motor 2 I will open VS Code?
In that case, once I switched back to monitor 1 (with Chrome) on motor 2 another Chrome tabs automatically popped up and VS code disappeared. 

So, is it possible to have a "separation" of tracking between browsers tab?

**Comment by sbmpost** [comment]
@GlibMartynenko 

Before going into the details, can you tell me which AutoRaise version you are running and which compile options / settings are in effect? This will help to reproduce what you are describing.

**Comment by GlibMartynenko** [comment]
in AutoRaise.mm file I see that version is 3.2
AUTORAISE_VERSION "3.2"

**Comment by sbmpost** [comment]
@GlibMartynenko 
AutoRaise tells Chrome to raise, which indeed makes Chrome raise all of its windows, even if on different displays. This behaviour can be circumvented if you specify -delay 0. This only works if you have the EXPERIMENTAL_FOCUS_FIRST compile time flag enabled. The README describes how to compile yourself a version that does. Note that by specifying delay 0, AutoRaise doesn't actually raise the window any longer but only moves the keyboard focus to it. Also note that this feature relies on undocumented Apple API calls, so it may break with future OSX releases. Nevertheless I am curious if this workaround is working for you.

**Comment by sbmpost** [comment]
@GlibMartynenko 
By the way, I noted that the behaviour you are reporting is actually a regression from v3.1 to v3.2, so you can also consider compiling v3.1 as a temporary workaround. In the meantime a fix for v3.2 has to be made (it will take some time though, as I am very busy these days)

**Comment by sbmpost** [comment]
@GlibMartynenko 
Testing some more, it seems that while moving the mouse between monitors, AutoRaise sometimes fails to Raise chrome within time, and tries again. The second time it tries messes things up. I am not sure if this is fixable, but I will have a look when I have time. Until then, the above workaround will have to do.

**Comment by sbmpost** [comment]
@GlibMartynenko 
A UI version has been released with many improvements. I am not sure if it will solve your problem, but it might be worth a shot, see: https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg
