### ISSUE TITLE
Can you do "normal", .app version?

### ISSUE THREAD

**Issue by sohate** [sbmpost/AutoRaise#90]
Because this https://github.com/sbmpost/AutoRaise doesn't update his version anymore. Please do the normal version. Thanks!

**Comment by sbmpost** [comment]
@sohate 
I am not sure what you mean with "normal version".

There are these options:

1. AutoRaise from github/sbmpost: this will always be the latest. Only thing you have to do is download and run "make install" as described in the readme. This gives you the latest app version.

2. AutoRaise via homebrew. Currently that version is at 3.1, which is one version behind the latest (3.2). If you need the latest you might want to ask @Dimentium to update.

3. AutoRaise with a gui on top of it with a "balloon" icon. I am not maintaining that repository. If you want that version, click
the bottom link in the readme and ask the maintainer about the repository status.

**Comment by Dimentium** [comment]
> 2. AutoRaise via homebrew. Currently that version is at 3.1, which is one version behind the latest (3.2). If you need the latest you can ask @Dimentium to update.

hmmm.. 
I missed it because there is no new "tag" here :/
https://github.com/sbmpost/AutoRaise/tags

**Comment by sbmpost** [comment]
@sohate 
You are completely right I forgot to tag the latest release. Will fix that right away 🙂 Thank you!

**Comment by sbmpost** [comment]
@sohate 
I am closing this issue because the tag was updated.
