### ISSUE TITLE
switching windows in chrome from gmail to notion window is not autofocused

### ISSUE THREAD

**Issue by UriZafrir** [sbmpost/AutoRaise#95]
Hello
After compiling autoraise with DEXPERIMENTAL_FOCUS_FIRST everything works quite well, except:

I found out that when switching windows in chrome from gmail to notion window is not autofocused
https://user-images.githubusercontent.com/35652384/179159171-c048f68d-a572-4900-9117-78f83acd9203.mov
Only when switching windows with cmd-tab does it focus the window.
Any way to solve this?

**Comment by sbmpost** [comment]
@UriZafrir 
I will have a look as soon as I am back from holiday. Thanks for reporting!

**Comment by sbmpost** [comment]
I made a lot of updates. I am not sure if it will solve your issue, but you might want to try with this [UI version](https://github.com/sbmpost/AutoRaise/blob/99-introduce-new-settings/AutoRaise.dmg)

**Comment by UriZafrir** [comment]
I've downloaded it and ran the dmg but nothing happened.

**Comment by UriZafrir** [comment]
after opening the dmg, going to the mounted system and copying to applications folder, giving it permissions and activating it, nothing happens..

**Comment by sbmpost** [comment]
So you *right* click the new balloon icon in the taskbar on the top right of your screen. Click preferences and change the settings as you like to have them. By default everything is disabled and indeed nothing happens.

**Comment by UriZafrir** [comment]
I think it's a great addition. Started using it.
Suggestion - maybe try to add an explanation in the gui for each effect..

**Comment by sbmpost** [comment]
> Suggestion - maybe try to add an explanation in the gui for each effect..

Good suggestion. Something for a next version though ;-)
Closing this issue now.
