### ISSUE TITLE
[Discussion] Another app called AutoRaise

### ISSUE THREAD

**Issue by hasantahir** [sbmpost/AutoRaise#96]
Hi,

Recently came across another app entitled, [AutoRaise](https://github.com/synappser/AutoRaise). While the app is relatively way less [feature-rich](https://synappser.github.io/apps/autoraise/), is there anything from the OS side that should prevent apps from having the same names?

Cheers

**Comment by sbmpost** [comment]
@hasantahir 
The OS will accept the same name. However you can’t have two AutoRaise.app files in the same Applications folder. That being said, this other person isn’t very original and could have done some research first before deciding on the same name. Let’s hope the source code is more unique ;-)

**Comment by sbmpost** [comment]
@hasantahir 
Ah and by the way, in the app store the name probably should be unique.
The other repo almost looks like an attempt to make money out of something that is open sourced and free if you ask me.

**Comment by hasantahir** [comment]
Awesome. My original thought was whether Apple has some powers to somehow blacklist one or the other. Hoping everything is resolved amicably.
