### ISSUE TITLE
Doesn't work with Safari fullscreen video.

### ISSUE THREAD

**Issue by sohate** [sbmpost/AutoRaise#98]
Hello! When I do fullscreen video in Safari (YouTube, for example) AutoRaise doesn't focus that window. Settings change haven't fix the problem. I hope you'll fix this issue. Thanks!

BTW, I'm using two displays: internal and external.

P.S. I'm using this version of the app: https://github.com/sbmpost/AutoRaise/blob/master/AutoRaise.dmg

**Comment by sbmpost** [comment]
@sohate 
I checked out what is going on. Apparently, the Safari full screen video window bears no title. AutoRaise assumes that if a window doesn't have a title, that it should not raise it. Many applications show dialogs without title which shouldn't be raised. So I am afraid the Safari exception is not easy to fix.

P.S. There is a new version: https://github.com/sbmpost/AutoRaise/blob/99-introduce-new-settings/AutoRaise.dmg

**Comment by sohate** [comment]
@sbmpost 

Well, your previous version works fine (with lhaeger GUI https://github.com/lhaeger). Has title, has no title - who cares? It works as it should be. I mean windows is a window, even dialogs with no title should be raised. Can you just add an option with this "no title should be raised" behaviour?

**Comment by sbmpost** [comment]
@sohate 
If you set the focus delay slider to 0 (i.e: only enable raise delay), then Safari should raise again just like before. You can download [v3.5.2](https://github.com/sbmpost/AutoRaise/blob/99-introduce-new-settings/AutoRaise.dmg)

**Comment by sohate** [comment]
Just test it! Works fine. Thank you very much!

**Comment by sbmpost** [comment]
@sohate 
all was merged to master.
